### ISSUE TITLE
Problems installing on macOS

### ISSUE THREAD

**Issue by carlca** [mholt/archiver#105]
- go version go1.11.2 darwin/amd64
- macOS 10.14.1 Mojave

Hello, I have just tried to run `go get -u github.com/mholt/archiver/cmd/archiver` and it comes back with...
```
package github.com/mholt/archiver/cmd/archiver: cannot find package "github.com/mholt/archiver/cmd/archiver" in any of:
	/usr/local/go/src/github.com/mholt/archiver/cmd/archiver (from $GOROOT)
	/Users/carlca/go/src/github.com/mholt/archiver/cmd/archiver (from $GOPATH)
```

I have Modules set to `GO111MODULE=auto`.

Any idea what the problem is?

**Comment by mholt** [comment]
These are using the old install instructions, but #103 fixed that (sorry!) -- use `go get -u github.com/mholt/archiver/cmd/arc` instead.

**Comment by carlca** [comment]
Thanks Matt! That sorted it!
