### ISSUE TITLE
NOTICE of concurrent use

### ISSUE THREAD

**Issue by wyxloading** [mholt/archiver#110]
https://github.com/mholt/archiver/blob/9866b6e2453eee43791b9e1b87d9e4c494985468/tar.go#L592
https://github.com/mholt/archiver/blob/9866b6e2453eee43791b9e1b87d9e4c494985468/tarbz2.go#L111
https://github.com/mholt/archiver/blob/9866b6e2453eee43791b9e1b87d9e4c494985468/tarxz.go#L104

I notice the `Archiver/Unarchiver` is not concurrent safe.
But what's more, even using `DefaultTar/DefaultTarBz2/DefaultTarXz` in multi goroutine may cause issues.
**We need more doc about this.**
Or just make `Archiver/Unarchiver` concurrent safe, and leave `Writer/Reader` as they should be new each time.

**Comment by mholt** [comment]
Well, you are right: the types are technically not safe for concurrent use. We could add a little note in the godoc about this I suppose, although generally I would not recommend assuming any documented value is safe for concurrent use unless the docs say it is, even in Go. Most standard library types that are thread-safe explicitly say so.

Feel free to submit a pull request with the change!

**Comment by mholt** [comment]
Added to godoc in daf9e77af2c7fca8b2883e0ef10f61eafba14a02
