### ISSUE TITLE
Make "format not recognized" error a const

### ISSUE THREAD

**Issue by onodera-punpun** [mholt/archiver#117]
https://github.com/mholt/archiver/commit/e1ccfb528128bf4ff3bd906823ae2dcb708f79f5#diff-635e4219ee55ef011b2b32bba065606bR405

That way we can do `if err != nil && err != archiver.ErrNotRecognized`.

**Comment by mholt** [comment]
Good idea -- except it'd be a `var` not a const. Care to submit a PR?
