### ISSUE TITLE
Add ByHeader support to all formats

### ISSUE THREAD

**Issue by onodera-punpun** [mholt/archiver#118]
Or at least, make it use this by default. The reason being that `ByExtension()` supports many more formats.

**Comment by mholt** [comment]
Can you explain more what you mean?

**Comment by onodera-punpun** [comment]
It seems like `ByHeader` Only supports three formats: https://github.com/mholt/archiver/blob/master/archiver.go#L411-L416

`ByExtension` supports many more: https://github.com/mholt/archiver/blob/master/archiver.go#L411-L416

So I'd be nice if `Unarchive` had a "method" parameter or something, that way the user can specify the use of `ByExtension` or `ByHeader` (used here: https://github.com/mholt/archiver/blob/master/archiver.go#L170)

**Comment by mholt** [comment]
Reading the header is technically superior since the extension can be misleading (as we've seen before) -- ideally, we'd check the headers for the compressed tar formats too, but I haven't implemented it.

Pull request welcome!

**Comment by mholt** [comment]
(This issue is good for beginners if you at least have experience working with file formats -- probably not awesome "first issue" if you're new to programming in general. So, like, good for Go beginners.)

**Comment by mholt** [comment]
During the holidays I took some time and completely rewrote this library in #302 and am preparing to merge and tag v4. In v4, all archive and compression formats can match by their file headers (by reading from the stream).
