### ISSUE TITLE
Support wildcard characters or some more regular expressions

### ISSUE THREAD

**Issue by rw209** [mholt/archiver#122]
That is request typical archivators, feature, like wildcard. `(*.*, *.ext, name.*)`

When i need use archiver for packing some format (only pdf, or something else), i should use bulkiness  `ioutil.ReadDir` + `filepath.Ext` or` filepath.Walk` +`filepath.Ext` metods
Maybe somebody else wants that feature in projekt?

**Comment by Inconnu08** [comment]
I would like to take on this

**Comment by mholt** [comment]
Use `filepath.Glob`: https://golang.org/pkg/path/filepath/#Glob

**Comment by Inconnu08** [comment]
@mholt seems like wild cards are already supported. You can close this.

**Comment by mholt** [comment]
I don't believe that is the case.

**Comment by Inconnu08** [comment]
@mholt when I run `arc archive test.tar.gz *.txt` or `arc archive test.tar.gz *file.*` it archives all the specific files.

**Comment by Inconnu08** [comment]
My bad, it was my change...pr-ing soon

**Comment by mholt** [comment]
@Inconnu08 Your shell is probably expanding that for you, not arc.

**Comment by Inconnu08** [comment]
@mholt thanks for pointing that out. You were right.
