### ISSUE TITLE
Don't `CheckExt` on `Archive`

### ISSUE THREAD

**Issue by josephlewis42** [mholt/archiver#123]
What do you think about removing the `CheckExt` requirement for the `Archive` function on zip files?

There are several alternative extensions that indicate a perfectly valid compressed file (e.g. JAR, docx, odt, gem), and this check adds an additional step to making them.

**Comment by mholt** [comment]
You raise a good point, but this check is necessary, and it's in place to ensure that bugs like the one in #90 where a tar archive was created with a zip extension.

Are you using this package to make docx files? 🤔

**Comment by josephlewis42** [comment]
As an alternative, what do you think about adding a parameter `IgnoreArchiveExtMismatch` (`false` by default to preserve existing functionality) to the archive struct to allow a developer to override it? Or, maybe adding a field that would let the developer override the extension?

```go
func (z *Zip) Archive(sources []string, destination string) error {
	err := z.CheckExt(destination)
	if err != nil && !z.IgnoreArchiveExtMismatch {
		return fmt.Errorf("checking extension: %v", err)
	}
```

I was hoping to use this library to produce and consume a new package format for a project I'm working on. The packages are just zips, but I wanted them to be identifiable by the extension because end-users shouldn't really be mucking around in them.

As an aside (not looking to sway your opinion :smile:), this is an awesome library. It feels extremely idiomatic, is well documented and "just works". I'm also a huge fan of your json-to-go tool.

**Comment by mholt** [comment]
As a much simpler, one-line-of-code workaround, why not simply rename the file after creating it?
