### ISSUE TITLE
archive multi directories got unexpect result

### ISSUE THREAD

**Issue by zkcrescent** [mholt/archiver#124]
I have two directories, test and test.copy (copy form test directory), run cmd `arc --mkdirs=true archive test.tar.gz ./test/ ./test.copy/`, then i got this 
`test.copy/
go.mod
go.sum
haha
shell.sh
test
test.go
test/
go.mod
go.sum
haha
shell.sh
test
test.go`
 how I can fix this? thanks for your help.

**Comment by mholt** [comment]
I don't think I understand. Can you format your question better?

**Comment by rw209** [comment]
Maybe he try to say that problem:
When i compress list files with subdirs. Archive on output have all files in root of archive.
Example:
i want compress *.go files in catalog "/home/user/go/src/BackupperVersions/"
this dir, have subdirs BackupperVersions/BackuperAlpha1, BackupperVersions/Backupper RC 1.0
when i compress with follow code:
```
func main() {
	fmt.Println("Hello World!")
	z := archiver.Zip{
		CompressionLevel:       flate.DefaultCompression,
		MkdirAll:               true,
		SelectiveCompression:   true,
		ContinueOnError:        false,
		OverwriteExisting:      false,
		ImplicitTopLevelFolder: true,
	}
	filelist := []string{
		"/home/user/go/src/BackupperVersions/",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1/backupper.go",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1/oldcleaner.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/Backupper",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/main.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/oldcleaner.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/packer.go",
	}
	_ = z.Archive(filelist, "test33.zip")
}
```
		
My test33.zip file have all *.go files in root of dir, and full subdirs with non *.go files
If i exclude any catalogs, and subdirs, archive will be content only go files in archve root, with out any subdirs. And i think "ImplicitTopLevelFolder: true," did not working (nothing change when i use this)

That's normal behavior?

**Comment by mholt** [comment]
Well, files listed in the `filelist` will be added to the root of the archive, and the documentation states this, so that's expected. Directories are recursively added, keeping their structure within the archive.

If ImplicitTopLevelFolder isn't working, go ahead and open a new issue with a detailed bug report: https://github.com/mholt/archiver/issues/new?template=bug_report.md - I updated the issue templates just a couple days ago. Please fill it out completely and provide a sample archive file if you can. Thanks!

**Comment by rw209** [comment]
Recursive adition for catalog it's ok, but how add files with their structures?

> // Archive adds all the files or folders in sources
>     // to an archive to be created at destination. Files
>     // are added to the root of the archive, and directories
>     // are walked and recursively added, preserving folder
>     // structure.

i Found it, in archiver - GoDoc, and sources, but i can't understand how add files with catalog structure
