### ISSUE TITLE
ImplicitTopLevelFolder mallfunction

### ISSUE THREAD

**Issue by rw209** [mholt/archiver#126]
## What version of the package or command are you using?
3.1 (see it from readme.md)

## What are you trying to do?
Try to create archive with top level folder by `ImplicitTopLevelFolder: true,` settings

## What steps did you take?

```
package main

import (
	"compress/flate"
	"fmt"

	"github.com/mholt/archiver"
)

func main() {
	fmt.Println("Hello World!")
	z := archiver.Zip{
		CompressionLevel:       flate.DefaultCompression,
		MkdirAll:               true,
		SelectiveCompression:   true,
		ContinueOnError:        false,
		OverwriteExisting:      false,
		ImplicitTopLevelFolder: true,
	}
	filelist := []string{
		"/home/user/go/src/BackupperVersions/",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1/backupper.go",
		"/home/user/go/src/BackupperVersions/BackuperAlpha1/oldcleaner.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/Backupper",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/main.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/oldcleaner.go",
		"/home/user/go/src/BackupperVersions/Backupper RC 1.0/packer.go",
	}
	_ = z.Archive(filelist, "test33.zip")
}
```
here is my code, and zip files with talking names
[TopLevelFalse.zip](https://github.com/mholt/archiver/files/2645581/TopLevelFalse.zip) [TopLevelTrue.zip](https://github.com/mholt/archiver/files/2645585/TopLevelTrue.zip)

## How do you think this should be fixed?
have no idea

## Bonus: What do you use archiver for, and do you find it useful?
For my self education lameBackupper project, Yes, that useful

**Comment by mholt** [comment]
Please fill out the rest of the issue template -- especially what you expected to happen, vs. what happened instead. Thanks.
