### ISSUE TITLE
Support Unarchive for .gz file

### ISSUE THREAD

**Issue by yangyadi1993** [mholt/archiver#129]
## What would you like to have changed?

I am using `Unarchive` function as a general function to unarchive files. All the other main types are supported very well. But I also want to use this function to unarchive `.gz` file, which is not supported. This is a very good library and very easy to use! I know you are working on this and I saw a lot of very recent commits. So I want to ask do you have any plans to add support for `.gz` in `Unarchive` function? If so, when? Thank you very much in advance!

## Why is this feature a useful, necessary, and/or important addition to this project?

`.gz` is a very common format and if we have supported some functions, could we put it to the general interface? That would be very nice!

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

I want to know if you are going to support this and what is the approximate time. If you won't support, I might want to use some other functions in the library and maybe write some code myself.

**Comment by mholt** [comment]
`.gz` is not an archive format, though... it is a compression format. What do you expect to have happen?

**Comment by yangyadi1993** [comment]
My mistake, then I am good! Thanks!

**Comment by mholt** [comment]
You can use `DecompressFile` to open gz files, if that's what you're looking for.
