### ISSUE TITLE
Travis build failing archiver not backwards compatible

### ISSUE THREAD

**Issue by jonpchin** [mholt/archiver#13]
Travis Build log(shortened to show relevant information):
go version go1.7.1 linux/amd64
...
gostuff/util.go:26: cannot call non-function archiver.Zip (type archiver.zipFormat)
gostuff/util.go:36: undefined: archiver.Unzip

Line 26 in util.go:
err := archiver.Zip(destination, source)
Line 36 in util.go:
err := archiver.Unzip(source, destination)

The travis build was successful last night, just pushed a commit tonight and noticed the travis build failing. I tested on my development and production environments and I do not encounter this error. I did not modify any code recently in my util.go file so I can only guess that this archiver package made an update within the past 24 hours that was not backward compatible.

The link to the travis build can be seen here https://travis-ci.org/jonpchin/GoChess/builds/166621466

**Comment by jonpchin** [comment]
I just took a quick glance at all the changes made in the past 24 hours, 

I see: 
Zip func was changed to Make and Unzip was changed to Open.

**Comment by mholt** [comment]
Are you sure you've pulled the latest? Our CI builds are passing...

**Comment by jonpchin** [comment]
On my machine I use for testing and on my production machine I am still using the archiver library I checked out a month ago and everything builds fine on there. The Travis builds always checks out the latest third party libraries every time it builds but I could be wrong.

**Comment by jonpchin** [comment]
I just now deleted the old archiver third party package and checked out go get github.com/mholt/archiver/cmd/archiver

I get the same error. That means the package is not backwards compatible.

**Comment by mholt** [comment]
archiver.Zip and archiver.Unzip no longer exist on master; call archiver.Zip.Make and archiver.Zip.Open instead. That should fix it!
