### ISSUE TITLE
Keep permissions on unzipped folders

### ISSUE THREAD

**Issue by heycait** [mholt/archiver#133]
## What would you like to have changed?
Retain the permissions when unzipping folders instead of hardcoding to `0755`

## Why is this feature a useful, necessary, and/or important addition to this project?
This feature is useful to maintain file integrity. It's unexpected that unzipping files changes it's permissions. 

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Our workaround has been using `git` to set the `core.filemode` to false, which requires us to unnecessarily include `git`.

**Comment by mholt** [comment]
Thanks for reporting the issue _and_ submitting a fix!
