### ISSUE TITLE
Files dont puts in root dir on zip archives

### ISSUE THREAD

**Issue by rw209** [mholt/archiver#136]
## What version of the package or command are you using?
latest on 06 jan 19

## What are you trying to do?
create typycal zip arch, as example code

## What steps did you take?
```
z := archiver.Zip{
		CompressionLevel:       flate.DefaultCompression,
		MkdirAll:               true,
		SelectiveCompression:   true,
		ContinueOnError:        false,
		OverwriteExisting:      true,
		ImplicitTopLevelFolder: false,
	}
_ = z.Archive([]string{"/home/user/go/src/testCatalog/"}, "/home/user/go/src/testArchLib/out.zip")
```

## What did you expect to happen, and what actually happened instead?
Should be: rootDir/other files
Have: rootDir, other files
(other files not putted in rootDir)
http://i.imgur.com/Ieneeb9.png that Pic

**Comment by mholt** [comment]
During the holidays I took some time and completely rewrote this library in #302 and am preparing to merge and tag v4. The new core APIs are completely stream-oriented and I believe issues with file placement in archives should be solved. We can reopen this if it is still an issue though.
