### ISSUE TITLE
Consider supporting afero

### ISSUE THREAD

**Issue by bkeroackdsc** [mholt/archiver#140]
## What would you like to have changed?
Consider adding support for https://github.com/spf13/afero which allows swapping in alternate filesystem implementations (for example, in-memory).

## Why is this feature a useful, necessary, and/or important addition to this project?

By using an abstract filesystem interface instead of the hard-coded stdlib functions, you allow users to optionally use in-memory or other lightweight filesystem functions instead of interacting with the real filesystem all the time. This is especially helpful in tests that use this library.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Right now users are forced to use a real filesystem whenever this library is used in tests.

**Comment by mholt** [comment]
This library supports streaming from any io.Reader or to any io.Writer -- no file system required: https://godoc.org/github.com/mholt/archiver#example-Zip--StreamingRead

**Comment by bkeroackdsc** [comment]
Ah, I missed that. Thank you!

**Comment by WhileLoop** [comment]
@mholt 
I am not able to to get that example to work. Using a http request results in content-length being 0. Using a response results in an error about needing a io.ReaderAt. 

What am I missing here?

**Comment by zartdinov** [comment]
Looks like it's unreal to extract large files on the fly because zip archives require random access for reading.
