### ISSUE TITLE
about doc's function list

### ISSUE THREAD

**Issue by hy05190134** [mholt/archiver#141]

**Comment by hy05190134** [comment]
when I use "err := archiver.CompressFile("test.tar", "test.tar.gz")"  the err will report "format specified by destination filename is not a recognized compression algorithm: test.tar.gz", but it is the function exampled by docs

**Comment by jbrockopp** [comment]
@hy05190134 I know this is a year later so likely not helpful, but incase it helps others, we were able to figure out how to work around this 👍 

We experienced the same issue with this code:

```go
package main

import (
	"fmt"
	"log"
	"os"

	archiver "github.com/mholt/archiver/v3"
)

func main() {
	defer func() {
		fmt.Println("Removing file example.tar...")

		err := os.RemoveAll("example.tar")
		if err != nil {
			log.Print(err)
		}

		fmt.Println("Removing directory extracted...")

		err = os.RemoveAll("extracted")
		if err != nil {
			log.Print(err)
		}
	}()

	files := []string{
		"index.html",
		"foo.txt",
		"testdata", // directory
	}

	fmt.Println("Archiving files...")

	err := archiver.Archive(files, "example.tar")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}

	fmt.Println("Compressing files...")

	err = archiver.CompressFile("example.tar", "compressed.tar.gz")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}

	fmt.Println("Decompressing files...")

	err = archiver.DecompressFile("compressed.tar.gz", "decompressed.tar")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}

	fmt.Println("Unarchiving files...")

	err = archiver.Unarchive("decompressed.tar", "extracted/example")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}
}

```

It **ALWAYS** seemed to fail on the call to `CompressFile()` and gave us the same error message you provided above:

> format specified by destination filename is not a recognized compression algorithm: compressed.tar.gz

We even attempted to mess with different file extensions (`.tgz`, `.zip` etc..) and still it didn't work. But we found that if we first create an archiver object, then attempt to archive/unarchive, it was successful:

```go
package main

import (
	"fmt"
	"log"
	"os"

	archiver "github.com/mholt/archiver/v3"
)

func main() {
	defer func() {
		fmt.Println("Removing file example.tgz...")

		err := os.RemoveAll("example.tgz")
		if err != nil {
			log.Print(err)
		}

		fmt.Println("Removing directory extracted...")

		err = os.RemoveAll("extracted")
		if err != nil {
			log.Print(err)
		}
	}()

	files := []string{
		"index.html",
		"foo.txt",
		"testdata", // directory
	}

	t := archiver.NewTarGz()

	fmt.Println("Archiving files...")

	err := t.Archive(files, "example.tgz")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}

	fmt.Println("Unarchiving files...")

	err = t.Unarchive("example.tgz", "extracted/example")
	if err != nil {
		log.Print(err)
		os.Exit(1)
	}
}
```

You'll note that we make no such call to `CompressFile()` directly, because the archiver object handles that internally 👍

**Comment by mholt** [comment]
During the holidays I took some time and completely rewrote this library in #302 and am preparing to merge and tag v4. In v4, the core APIs don't care about filenames except for optional matching with a format type, and I believe this issue should be solved.
