### ISSUE TITLE
Unlink the symbolic link if it already exists

### ISSUE THREAD

**Issue by jchionh** [mholt/archiver#143]
The function `writeNewFile()` overwrites the file if it already exists. Following the same behavior, should `writenewSymbolicLink()` also overwrite the symbolic link if it already exists?

If this is agreeable, I propose to do so by checking if the symlink exists, and unlink using `os.Remove()` if true, before doing `os.SymLink()`

**Comment by jchionh** [comment]
Referencing this function:
https://github.com/mholt/archiver/blob/master/archiver.go#L313

**Comment by mholt** [comment]
Hm, yes, that seems like a good idea; they are used in parallel just depending on the file mode.

**Comment by jchionh** [comment]
https://github.com/mholt/archiver/pull/145

**Comment by jchionh** [comment]
PR #145 was merged, closing this issue.
