### ISSUE TITLE
Extract single file without recreating its path

### ISSUE THREAD

**Issue by MarkusFreitag** [mholt/archiver#146]
I try to extract a single file from an archive. This works fine so far, but it seems that unfortunately there is no way to just put it into a directory. It's original path, from inside the archive, is always recreated. Do I miss anything that would help to achieve this?

P.S. Thank you for creating/maintaining this useful project =)

**Comment by mholt** [comment]
Using archiver's CLI or as a library?

**Comment by MarkusFreitag** [comment]
I'm using it as a library.

**Comment by hy05190134** [comment]
@MarkusFreitag  you can check whether is the question like this : https://github.com/mholt/archiver/pull/142

**Comment by mholt** [comment]
(Good point -- thanks for commenting. Please continue looking into this, as I will be swamped finishing my thesis for a couple weeks.)

**Comment by hy05190134** [comment]
@mholt  you can think of my pull request and give some advice

**Comment by MarkusFreitag** [comment]
If I understood the mentioned PR correctly, my case is different to that. My archive contains a file under `bin/example.file`. When I call `extr.Extract("archive.tar.gz", "bin/example.file", "/tmp")`, it gets written to `/tmp/bin/example.file`.
But I want to place it directly to `/tmp/example.file` without the need of moving it after the extraction. So what I try to achieve is, to extract the single file without it's original path from inside the archive.

**Comment by hy05190134** [comment]
@MarkusFreitag  it is new feature for you, and it has risks for "aa/tt.file" and "bb/tt.file", it will overlap in  your ways

**Comment by MarkusFreitag** [comment]
I understand that the current behaviour is totally fine and what the user would expect. Initially I was just asking whether there is already a way to achieve this case using the library.
If not maybe we can add another extract method which just extracts **one** file to a specific destination path.

**Comment by Kriechi** [comment]
I think I just run into the same issue.
I want to extract a single file into a destination directory: 
`archiver.Extract("foo.zip", "some/foo/path/picture.jpg", "/home/user/Downloads")`. 
I expect the final result to be a new file `/home/user/Downloads/picture.jpg`.
But instead I got `/home/user/Downloads/some/foo/path/picture.jpg`. I don't want all these subfolders.

However, this seems to work as I expect it for directories in the archive:
`archiver.Extract("foo.zip", "some/foo/path/", "/home/user/Downloads")
and I got, as expected: `"/home/user/Downloads/path/"` with a single `picture.jpg` inside.

Yes... I could simple `mv` everything inplace where I want it to be, but this is terrible UX during a large extraction when files suddenly move away...

**Comment by mholt** [comment]
During the holidays I took some time and completely rewrote this library in #302 and am preparing to merge and tag v4. The new APIs let you choose precisely how to handle each extracted file by not presuming anything at all; you just give it a callback function that does what you want with it. Please check it out and let me know if you have any feedback!
