### ISSUE TITLE
how about add an option to specify non-utf8 encoding of zip filename

### ISSUE THREAD

**Issue by zxdvd** [mholt/archiver#147]
## What would you like to have changed?
I'd like to add an option like `-encoding` or `-O` just like unzip to specify the filename encoding of zip file.

## Why is this feature a useful, necessary, and/or important addition to this project?
I work with mac and linux server but lots of colleagues work with windows. I have much terrible experience with zip files from them. The filenames always got messy. I think lots of people suffer same things.

It's easy to implement and lots of people will benefit.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
The unzip has a option `-O` but it seems that the default unzip on osx do not have this option.

**Comment by hy05190134** [comment]
@zxdvd  author is very busy

**Comment by mholt** [comment]
Yep, will get around to things eventually

**Comment by zxdvd** [comment]
I just submitted a PR for this. Could you help to review it?

**Comment by mholt** [comment]
@zxdvd Thank you very much for the contribution, I learned something new from it. Sorry I didn't get around to it for a couple years. I implemented your change in #302 which is a complete library rewrite, and gave you credit in the code and in the commit. Thanks again for contributing
