### ISSUE TITLE
Fails to install on Windows 10

### ISSUE THREAD

**Issue by Phillip-Gabler** [mholt/archiver#151]
## What version of the package or command are you using?
3.1.1

BUT... I noticed that the code installed on Linux and Windows is different. The linux install worked, while the windows install did not. I will look into what is different on the two platforms, then will update the Issue appropriately.

## What are you trying to do?
go get github.com/mholt/archiver on Windows 10

Response:

C:\Users\pgable000>go get github.com/mholt/archiver
# github.com/mholt/archiver
C:\zSandbox\GoWorkspace\src\github.com\mholt\archiver\lz4.go:19:10: w.Header.CompressionLevel undefined (type lz4.Header has no field or method CompressionLevel)
C:\zSandbox\GoWorkspace\src\github.com\mholt\archiver\tarlz4.go:87:14: lz4w.Header.CompressionLevel undefined (type lz4.Header has no field or method CompressionLevel)

Using go version go1.11 windows/amd64

## What steps did you take?
go get github.com/mholt/archiver on Windows 10

## What did you expect to happen, and what actually happened instead?
Install fine on Linux. Expected the same on Windows 10.

## How do you think this should be fixed?
The lz4.Header from pierrec/lz4 does NOT have the CompressionLevel int member.

// Header describes the various flags that can be set on a Writer or obtained from a Reader.
// The default values match those of the LZ4 frame format definition (http://fastcompression.blogspot.com/2013/04/lz4-streaming-format-final.html).
//
// NB. in a Reader, in case of concatenated frames, the Header values may change between Read() calls.
// It is the caller responsibility to check them if necessary (typically when using the Reader concurrency).
type Header struct {
	BlockDependency bool   // compressed blocks are dependent (one block depends on the last 64Kb of the previous one)
	BlockChecksum   bool   // compressed blocks are checksumed
	NoChecksum      bool   // frame checksum
	BlockMaxSize    int    // the size of the decompressed data block (one of [64KB, 256KB, 1MB, 4MB]). Default=4MB.
	Size            uint64 // the frame total size. It is _not_ computed by the Writer.
	HighCompression bool   // use high compression (only for the Writer)
	done            bool   // whether the descriptor was processed (Read or Write and checked)
	// Removed as not supported
	// 	Dict            bool   // a dictionary id is to be used
	// 	DictID          uint32 // the dictionary id read from the frame, if any.
}

What are the possible values for CompressionLevel, and which ones are considered HighCompression?

In lz4.go, on line 19, evaluate lz.CompressionLevel, and set w.Header.HighCompression appropriately:

// Compress reads in, compresses it, and writes it to out.
func (lz *Lz4) Compress(in io.Reader, out io.Writer) error {
	w := lz4.NewWriter(out)
	
	if lz.CompressionLevel == 9 ) {
		w.Header.HighCompression = true
	}
	defer w.Close()
	_, err := io.Copy(w, in)
	return err
}

This change compiles and runs. It seems to work.

## Please link to any related issues, pull requests, and/or discussion
None.

## Bonus: What do you use archiver for, and do you find it useful?
Trying to improve upon go's decompression packages.

**Comment by Phillip-Gabler** [comment]
You can close this issue. I deleted the sources and reinstalled them, and the problem no longer exists.

**Comment by gesquive** [comment]
I've run into this same issue. Cleared my go cache and modcache, still pops up the same error when I go get the v3.1.1 package. @Phillip-Gabler What do you mean by deleted the sources?

```
> go clean -cache -modcache
> go get github.com/mholt/archiver@v3.1.1
go: finding github.com/mholt/archiver v3.1.1
# github.com/mholt/archiver
../../../gowork/pkg/mod/github.com/mholt/archiver@v3.1.1+incompatible/lz4.go:19:10: w.Header.CompressionLevel undefined (type lz4.Header has no field or method CompressionLevel)
../../../gowork/pkg/mod/github.com/mholt/archiver@v3.1.1+incompatible/tarlz4.go:87:14: lz4w.Header.CompressionLevel undefined (type lz4.Header has no field or method CompressionLevel)
```
