### ISSUE TITLE
Support for Zip / Rar "aliases"

### ISSUE THREAD

**Issue by matthjes** [mholt/archiver#154]
## What would you like to have changed?

Allow "aliases" for zip and rar files, i.e. make the allowed extensions configurable.

## Why is this feature a useful, necessary, and/or important addition to this project?

I'd like to use archiver to extract images from comic files. These files often have the extensions cbz (= zip) or cbr (= rar). They are perfectly fine zip or rar files with a different extension to show that these are comic reader files. Currently these formats are not recognized as archiver uses the file extension to determine the file type. It would be great if one can provide a list of extension "aliases" for different file types, e.g. "if the extension is zip or cbz, then use zip, if it's rar or cbr use rar".

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

I'm coming from Java, where the input for the classes responsible for handling zipped files is an input stream, so the file extension is not used at all and it's irrelevant which extension the original file had.

**Comment by mholt** [comment]
I guess that's possible, but rather than add more complexity to this project, why not just rename the files?

**Comment by matthjes** [comment]
I would have to rename a lot of files, several thousands. Besides, cbr and cbz are the quasi-standard extensions for comic files.
Another example: Javas jar files are just zip files with another extension.

I've forked the code and added a "Extensions []string" field. Then I just initialized the ExtensionCheckers array with the respective extensions, e.g.:
```go
&Rar{
  Extensions: []string{".rar", ".cbr"},
},
```
and added a check inside the CheckExt functions:
```go
func (z *Zip) CheckExt(filename string) error {
  ext := path.Ext(filename)
  extFound := false

  for _, e := range z.Extensions {
    if e == ext {
      extFound = true
      break
    }
  }
  if !extFound {
    return fmt.Errorf("filename must have a .zip extension")
  }
  return nil
}
```
Not very elegant, but it's a solution for now. What's missing is a way to configure the archiver with the extensions for the individual formats.

**Comment by mholt** [comment]
That's not a bad solution actually. I suppose that each type will need an unexported, default list of extensions if the Extensions field is not set.

Before you submit a pull request though, I just had one question:

> I'm coming from Java, where the input for the classes responsible for handling zipped files is an input stream, so the file extension is not used at all and it's irrelevant which extension the original file had.

Do you mean that the file type is predefined beforehand, or that the file header is read from the stream directly? Because if the latter, archiver can do that too, I just don't think we've implemented it for all file types quite yet. If that's an option for you, maybe we should finish implementing that for each file type before adding customizable extensions...

**Comment by matthjes** [comment]
As far as I understood it, the stream is checked while reading if it's contents can be decompressed, so I guess the header / leading bytes are checked.
You work with it like this:
```java
ZipInputStream stream = new ZipInputStream(<input stream>); // <input stream> ca be, e.g., a file stream
ZipEntry entry = stream.getNextEntry();
if (entry != null) {
  // process entry
}
```
You walk through the stream similar to an iterator, calling `ZipInputStream.getNextEntry()` until it returns null. It returns also null right at the start if the stream cannot be decompressed / is not a zipped stream.

This would be an alternative to providing the extensions.

**Comment by mholt** [comment]
Someone would just have to finish implementing the Matcher interface here: https://github.com/mholt/archiver/blob/master/zip.go#L524

Once that is implemented for all the types, it can be used instead of extensions.

**Comment by matthjes** [comment]
Hm, how would you implement this for, e.g., tar.gz files? Here you first need to use the .gz matcher, extract the file and then use the .tar matcher. Would you call the matchers multiple times (e.g. in case of .tar.gz, the .gz matcher matches, the files get extracted; if its a single file, then check all matchers again -> the .tar matcher matches).

**Comment by mholt** [comment]
> I would have to rename a lot of files, several thousands.

One other thought on this is that if you're using archiver as a library (or in any other way automating its use) all you have to do is rename the file, run archiver, then name it back to its original name afterward. It's like 2-4 extra lines of code.

> Hm, how would you implement this for, e.g., tar.gz files?

I'm not sure, which is why I haven't done it. :) How does your Java lib do it?

**Comment by FerdieBerfle** [comment]
None of these changes would be necessary if all files types were handled 'ByHeader' instead of 'ByExtension'.

In other words, read enough to see that it is a zip archive, then use zip to extract the contents.  The name/extension shouldn't matter at all.

**Comment by mholt** [comment]
Yes, I think that is a better approach. Thanks!

**Comment by benjamindean** [comment]
Any solutions on this one? I would like to avoid renaming files.
