### ISSUE TITLE
Completion support

### ISSUE THREAD

**Issue by soullivaneuh** [mholt/archiver#156]
## What would you like to have changed?

Having completion support like `arc completion [zsh|bash|fish]`

## Why is this feature a useful, necessary, and/or important addition to this project?

Useful to install completion with ease and make command usage easier.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

N/A

**Comment by mholt** [comment]
This would be cool, yeah.

However, as I don't have plans/time to make a command for v4 (unless sponsorships motivate it specifically), I'll close this issue; but I've labeled it with "command" so we can remember this if someone does end up contributing a command later. Thanks!
