### ISSUE TITLE
How to add a hardlink to archive?

### ISSUE THREAD

**Issue by AlexAkulov** [mholt/archiver#158]
Hello! 
I use this way to add regular file to archive:
https://github.com/AlexAkulov/clickhouse-backup/blob/d1677be5f661ba9c925aadaac72b6e79bdcecbd8/s3.go#L157-L163
But I don't understand how to add a hardlink to archive. Do you have any example about it?

**Comment by mholt** [comment]
If this is still an issue in v4, let me know and we can reopen this. (v4 has an option to preserve links.)
