### ISSUE TITLE
support excluding directories 

### ISSUE THREAD

**Issue by jackytck** [mholt/archiver#16]
I'd like to make a PR to exclude certain directories when archiving.

So we just need to pass down a slice of excluded paths to filepath.Walk, then return filepath.SkipDir if the path matches any of the excluded path?

What do you think?

**Comment by mholt** [comment]
Sure this is easy, but the purpose of archiver is to mimic your OS's file explorer's "right-click and click Compress" functionality, and I really like the simplicity of its API as-is. Can this be done without changing the function signatures or simple usage?

**Comment by jackytck** [comment]
I also like the simplicity. And I don't want to pollute that. Seems that there's no way of passing additional options without changing `Make(destination string, sources []string) error`. Making a new function e.g. sth like MakeAdvance(), is not very elegant to me. So I just fallback to use tar, anyway. Thanks.

**Comment by mholt** [comment]
Okay. Sorry about that. I'd rather keep the scope of this project narrow. I invite others to create other applications that build on it if they wish!

**Comment by mholt** [comment]
Should be possible now after #99 is in. Each archiver will have a configuration struct that could potentially be used to exclude files.
