### ISSUE TITLE
Wrong constructor for Lz4?

### ISSUE THREAD

**Issue by alixaxel** [mholt/archiver#160]
## What version of the package or command are you using?
bfece90dc3bb7199e8a397a27eb267a6cdd9589c

## What did you expect to happen, and what actually happened instead?
On:

https://github.com/mholt/archiver/blob/bfece90dc3bb7199e8a397a27eb267a6cdd9589c/archiver.go#L460-L463

## How do you think this should be fixed?

I believe the above is an oversight and should instead be:

```go
 case *Bz2: 
 	return NewBz2(), nil 
 case *Lz4: 
 	return NewLz4(), nil 
```

**Comment by mholt** [comment]
Ah yup, thanks for catching that. Want to submit a quick PR?

**Comment by alixaxel** [comment]
@mholt :+1: Couldn't find a `CONTRIBUTING`, but should be enough, right?

**Comment by mholt** [comment]
@alixaxel Yeah, thanks.
