### ISSUE TITLE
Brotli Support

### ISSUE THREAD

**Issue by alixaxel** [mholt/archiver#161]
## Introduce the format you are requesting.

**Brotli**:

- High compression ratio.
- Slow compression speed.
- Fast decompression speed.

Developed by Google and used in a plethora of tools (browsers, nginx, Node.js, ...).

## What do YOU use this format for?
Asset pre-compression (for the web) is usually the main use case but can also be used to achieve maximum compression of large binaries ([`alixaxel/chrome-aws-lambda`](https://github.com/alixaxel/chrome-aws-lambda)) for instance.

## What is the format's conventional file extension(s)?
```
.br
```

## Please link to the format's formal or official specification(s).
https://tools.ietf.org/html/rfc7932

## Which Go libraries could be used to implement this format?

* https://godoc.org/github.com/dsnet/compress/brotli

There are more libraries that are able to write, but they all seem to rely on `cgo`.

**Comment by mholt** [comment]
Still waiting for a pure Go compressor implementation.

**Comment by JalonSolov** [comment]
https://github.com/andybalholm/brotli

**Comment by alixaxel** [comment]
@JalonSolov Amazing! How reliable is this `c2go` tool?

**Comment by mholt** [comment]
@alixaxel That project is in a usable state, I've already implemented into Caddy 2. Feel free to submit a PR.

**Comment by mholt** [comment]
I just went ahead and took 10 minutes to add it.

However, the tests seem to fail with it, unfortunately.

**Comment by mholt** [comment]
Nevermind, fixed the panic in d3de269f4e3994bbf03462d448cb215e27efc405. Should work now.
