### ISSUE TITLE
Create shorthands for parameters such as u for unarchive.

### ISSUE THREAD

**Issue by onodera-punpun** [mholt/archiver#167]
## What would you like to have changed?
Create shorthands for parameters such as u for unarchive.

## Why is this feature a useful, necessary, and/or important addition to this project?
unarchive is very tedious to write.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Probably create a wrapper.

**Comment by mholt** [comment]
Hmm, writing out a word isn't very much of a concern to me, and it's clear what is happening this way, rather than a single letter `u`.
