### ISSUE TITLE
Zstandard support.

### ISSUE THREAD

**Issue by klauspost** [mholt/archiver#170]
## Introduce the format you are requesting.

Zstandard / `zst` + `tar.zst` support

## What do YOU use this format for?

Logs, backups, anything.

## What is the format's conventional file extension(s)?

`zst`

## Please link to the format's formal or official specification(s).

https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md

## Which Go libraries could be used to implement this format?

https://github.com/klauspost/compress/tree/master/zstd#zstd

I should pretty much be as easy as the gzip implementation.

Mostly, it would be nice to have an easy to use tool for me to do my testing.

**Comment by mholt** [comment]
On it!

What is the standard file extension for tar+zst? `.tar.zst`?

**Comment by klauspost** [comment]
tar.zst I believe.

**Comment by mholt** [comment]
@klauspost Thanks; it's halfway done.

I'm also wanting to make this package a Go module; can I ask a favor? :smile: It would be helpful -- necessary -- for https://github.com/klauspost/compress/issues/121 to be resolved... let me know if you need any help with that.

**Comment by klauspost** [comment]
Yeah, I think I'll just include it in the repo. I'll put it next on my list!

**Comment by mholt** [comment]
Cool, thanks!

I've pushed 3971425a20f07db6ce935819231bbda3482d18d0 which should add full zstd support to the command, as well as tar.zst. I'm going to work on updating our CI tests now until modules are ready.

**Comment by klauspost** [comment]
If you have the chance, I have added https://github.com/klauspost/compress/pull/123 to fix the modules situation. If it will be good enough for you, I'll merge it and do a release.

**Comment by mholt** [comment]
@klauspost I suppose so; I'm not actually sure how to test it for sure until it gets merged 😅 but from the looks of it, that should help. I can wait until fd0 confirms that, thanks!

**Comment by sergeevabc** [comment]
Err… How do I use `-19 --long` switches of Zstandard here (as they increase the degree of compression)?
