### ISSUE TITLE
Help output is too long and lacks examples

### ISSUE THREAD

**Issue by mvdan** [mholt/archiver#174]
## What version of the package or command are you using?

v3.2.0

## What are you trying to do?

Figure out how to use arc, making many mistakes in the process.

## What steps did you take?

Try running commands like `arc` or `arc help`, expecting to see quick examples to create and extract archives.

## What did you expect to happen, and what actually happened instead?

See maybe 20 or so lines of output, containing very simple examples like the ones you see in the README:

    arc archive test.tar.gz file1 file2
    arc unarchive test.tar.gz

Instead, I got about two full pages of output, and no examples. Most of the output is somewhat irrelevant, if all I want is a quick idea of what the tool does and how to use it.

## How do you think this should be fixed?

Vastly cut the amount of output from the help output. It should be short and point people in other directions if they want to read more about certain operations. For example, `arc help` could point at `arc help archive` or `arc archive -h` if the user wants to know more about compression.

Another option is to link to the README file, and have all the details there.

And add a couple of examples, as shown above. Adding examples while keeping the amount of output isn't helpful in my opinion though, as few people will read through all that or even see that there are examples buried in the output.

## Bonus: What do you use archiver for, and do you find it useful?

To replace `dtrx`, which served a similar purpose, but is abandoned and doesn't support archiving.

**Comment by mholt** [comment]
The command help could have definitely been improved.

As I don't have plans/time to make a command for v4 (unless sponsorships motivate it specifically), I'll close this issue; but I've labeled it with "command" so we can remember this if someone does end up contributing a command later. Thanks!
