### ISSUE TITLE
Opt out of extension checks

### ISSUE THREAD

**Issue by ns-cweber** [mholt/archiver#175]
## What would you like to have changed?
Remove the errors when the output file path doesn't end in a particular extension (https://github.com/mholt/archiver/blob/master/targz.go#L40). As far as I can tell, these checks are just enforcing a file naming convention; I don't think they help ensure correctness. Seems like the extension checking could be made optional, ideally be decoupling it from the archive action.

## Why is this feature a useful, necessary, and/or important addition to this project?
My project builds artifacts and puts them in a file store where the file names are the checksums.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
As a workaround, I'm writing to a tempfile with the required extension (.tar.gz, in my case) and then renaming the file to the checksum.

**Comment by mholt** [comment]
Well, the extension is actually really important. If you need a different file name, just rename it later like you're doing.

History:
- https://github.com/mholt/archiver/issues/123
- https://github.com/mholt/archiver/issues/90
