### ISSUE TITLE
Close errors silently ignored

### ISSUE THREAD

**Issue by abourget** [mholt/archiver#184]
In latest `master`, the signature of `cleanupFunc` is `func()`, silences errors. Its use through is mostly through `defer` which also silently ignore errors.

All of the `.Close()` funcs silently ignore the error (because `cleanupFunc` doesn't handle it), therefore, if for some reasons (and I've found ways that `zstd` errors on Close), any `.Close()` fail, then you're out of luck, and end up with borked archives.

Refs: 
```
tarbrotli.go:82:	tbr.Tar.cleanupWrapFn = func() {
tarsz.go:83:	tsz.Tar.cleanupWrapFn = func() {
tarlz4.go:90:	tlz4.Tar.cleanupWrapFn = func() {
tarbz2.go:88:	tbz2.Tar.cleanupWrapFn = func() {
tarbz2.go:100:	tbz2.Tar.cleanupWrapFn = func() {
targz.go:95:	tgz.Tar.cleanupWrapFn = func() {
targz.go:111:	tgz.Tar.cleanupWrapFn = func() {
tarxz.go:85:	txz.Tar.cleanupWrapFn = func() {
tarzst.go:82:	tzst.Tar.cleanupWrapFn = func() {
tarzst.go:94:	tzst.Tar.cleanupWrapFn = func() {
```

## Proposed fix

Its use in:
```
tar.go:185:		defer t.cleanupWrapFn()
```

is not wired up to return an error from `t.cleanupWrapFn()`.

I propose something like:
```
func... (...) (err error) {
   ...
   defer func() {
      err2 := t.cleanupWrapFn()
      if err == nil {
          err = err2
      }
   }()
```

**Comment by mholt** [comment]
Thanks for pointing this out. I'm not sure what good reporting the error from closing will do though, especially if there's another error already. If it fails to close, you can't really do anything about it; and if there's another error, you have to choose which one to report. The close errors seem less important.

I'm open to the suggested fix, but it'll have to be contributed on top of #302, maybe after it gets merged or maybe I'll find the energy to do it before then. :)

**Comment by mholt** [comment]
Thinking more on this, I'm not sure what we'd really do with errors from Close(). It's not like you can fix the archive...

Closing this issue. If that is an error (heh), please let me know more information (what are the specific errors you're getting from Close(), what can I do to reproduce the problem, and why is it causing a problem for you / what should be done). Thanks!
