### ISSUE TITLE
Performance Improvements with DEFLATE?

### ISSUE THREAD

**Issue by marklit** [mholt/archiver#188]
I've [benchmarked](https://tech.marksblogg.com/faster-zip-decompression-unzip-deflate-zlib-crc32-adler32-7zip-archiver.html) decompressing a 267 MB ZIP archive using DEFLATE with Archiver 3.2.0 and six other tools and methods and Archiver came out being the slowest, it was over 2x slower than using Python 2.7 and zlib-ng. Archiver appears to use SSE 4.2 and AVX op codes but I'm uncertain these are being used in the decompression process.

Are there any performance-related patches that might help improve Archivers performance? Is there something I could do with the build process to speed up decompression of DEFLATE data?

**Comment by mholt** [comment]
I'll defer to @klauspost for this one. 😅 He's a lot smarter than me when it comes to this stuff!

I only ever use this for small stuff and not in hot paths, so I haven't personally been too concerned about performance. But I'm totally down if someone wants to improve it!

**Comment by klauspost** [comment]
@mholt I haven't looked much into inflate (decompression) performance. However, it shouldn't be terrible - although decompression speed is the main problem with deflate.

However, the (stdlib) package does make a 'promise' that it will never read beyond the end of the stream. That makes it quite inefficient, since it has to do a read operation, basically one byte at the time.

I think you would see a significant speed increase if you inserted a buffer in [DecompressFile](https://github.com/mholt/archiver/blob/e1ccfb528128bf4ff3bd906823ae2dcb708f79f5/filecompressor.go#L46). I can send a PR with that change.

**Comment by klauspost** [comment]
@marklit Some feedback on your article. Hope you don't mind.

The decompression part is typically referred to as 'inflate'.

> Alder-32 is used for DEFLATE compression

Deflate does not have any checksum. You might be thinking of "ZLIB (RFC 1950)" streams. Those are fairly uncommon 'in the wild'.

> Vectorisation 

Typically there isn't much to be gained from vectorisation when dealing with compression. Every output byte depends on the previous value, so there is no magic "8 bytes of data are being handled in each iteration" to be had here. 

BMI/BMI2 instructions can help you for certain tasks, but they are not vector instructions.

> The above isn't proof that those op codes were executed in the code paths

Yeah, that makes it all a bit speculative.

Honestly my main conclusion would be to not use a deflate-based compression scheme if decompression speed is even somewhat important. While you might be forced to use it, there are better alternatives (eg. zstandard), that are just straight up better.

**Comment by marklit** [comment]
Thanks for looking into that @klauspost, shame it didn't make a difference. Cheers for the blog feedback as well. I'll probably include these with a few other updates in the coming weeks.

The ZIP files I can't do much about, I have been given a few million of them that were produced over a decade ago in some cases.

**Comment by mholt** [comment]
Thanks for the input, @klauspost! :+1:

I guess I will close this? If anything actionable comes about we can reopen it.
