### ISSUE TITLE
when install dependencies package report unrecognized import path "math/bits"

### ISSUE THREAD

**Issue by lyenrowe** [mholt/archiver#189]
G:\go\src\lyen>go get -u -v github.com/mholt/archiver/cmd/arc
github.com/mholt/archiver (download)
github.com/andybalholm/brotli (download)
github.com/dsnet/compress (download)
github.com/golang/snappy (download)
github.com/klauspost/compress (download)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
github.com/klauspost/pgzip (download)
github.com/nwaples/rardecode (download)
github.com/pierrec/lz4 (download)
github.com/ulikunitz/xz (download)
github.com/xi2/xz (download)

G:\go\src\lyen>go version
go version go1.8 windows/amd64

what math/bits package come from, is it my golang version too old?.
Ok, I can see the package in https://godoc.org/math/bits. Why, can't download this automatic, when package have no host prefix. Should I update my go version or not?

**Comment by mholt** [comment]
Yes, update your Go version. :)

Feel free to comment again if that does not work!
