### ISSUE TITLE
Tag v3.2.1 (or v3.3.0) to improve module support

### ISSUE THREAD

**Issue by nmiyake** [mholt/archiver#191]
## What would you like to have changed?
The repository state at (or after) commit 7598309 should be tagged as v3.2.1 or v3.3.0

## Why is this feature a useful, necessary, and/or important addition to this project?
This will complete the support for go modules implemented by #190 and allow the module to be added as a dependency by running `go get github.com/mholt/archiver/v3`

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Until this is done, adding this dependency as a module requires explicitly specifying the "mater" branch (or a specific commit at or after 7598309). For example:

```
➜ go get github.com/mholt/archiver/v3@master
go: finding github.com/mholt/archiver master
go: finding github.com/mholt master
go: finding github.com/mholt/archiver/v3 master
go: finding github.com master
go: downloading github.com/mholt/archiver/v3 v3.2.1-0.20191114030510-7598309d46f5
go: downloading github.com/mholt/archiver v1.1.3-0.20191030054347-58e2c146a020
go: extracting github.com/mholt/archiver v1.1.3-0.20191030054347-58e2c146a020
go: extracting github.com/mholt/archiver/v3 v3.2.1-0.20191114030510-7598309d46f5
➜ cat go.mod 
module foo

go 1.13

require github.com/mholt/archiver/v3 v3.2.1-0.20191114030510-7598309d46f5 // indirect
```

## Please link to any relevant issues, pull requests, or other discussions.
PR to use proper module name was #190 and has been merged.

**Comment by mholt** [comment]
Done, thanks!
