### ISSUE TITLE
Support war file (Java web package)

### ISSUE THREAD

**Issue by nianjiang** [mholt/archiver#194]
## Introduce the format you are requesting.
war file, is the  type of java web package.
Naturally， it is same with zip, using zip function can Unarchive the war file.

**Comment by JalonSolov** [comment]
This would "just work" if ByHeader support were added to more formats.  All zip files would be handled as zip files, regardless of file extension.  Truthfully, ByHeader should always be the default, since file extensions are wrong far too often.

**Comment by mholt** [comment]
If it is in fact same as zip, then @JalonSolov is right, and this is now implemented in #302, which will become v4 of this package.
