### ISSUE TITLE
Version subcommand 

### ISSUE THREAD

**Issue by Croissong** [mholt/archiver#196]
## What would you like to have changed?
Provide an `archiver version` subcommand to display its current version corresponding to the github release tag.

## Why is this feature a useful, necessary, and/or important addition to this project?
I don't believe it's currently possible to figure out the used version, or is there? 

Thanks in advance :)

**Comment by coolaj86** [comment]
@mholt I'd be willing to add this such that `arc version` outputs a version number.

Given no other direction I would use either `goreleases` or copy https://git.rootprojects.org/root/go-gitver/src/branch/master/gitver/gitver.go into `tools/gitver.go` and add a `go generate` command.

However, I know that you are particular about how things are done, so I'd like to solicit your take on the matter as to how this could be implemented to your liking.

**Comment by coolaj86** [comment]
I suggest this subcommand:

```bash
arc version
```

And this as the output:

```txt
arc (archiver) v3.3.0 (g3719b73) 2020-07-17T21:03:06 2020
```

**Comment by Dean-Coakley** [comment]
@coolaj86 This can be closed too?

Implemented in: https://github.com/mholt/archiver/pull/236

**Comment by Croissong** [comment]
I assume it can, since @coolaj86 implemented it himself. Thanks a bunch you guys :)
