### ISSUE TITLE
 PR: Reader and Writer support

### ISSUE THREAD

**Issue by zolnov** [mholt/archiver#20]
Hi,
Please consider to provide exported functions having `Reader` / `Writer` as argument instead of file names too (where possible). It would make the library more flexible by enabling streaming, buffering, in-memory use-cases. Thanks.

**Comment by SeerUK** [comment]
It would also potentially make testing easier too.

**Comment by mholt** [comment]
Thanks to @jservice-rvbd this was implemented in #43

**Comment by mholt** [comment]
See #99 for a revamp of this feature.
