### ISSUE TITLE
support io.Reader/io.ReaderAt for Walker

### ISSUE THREAD

**Issue by junfengye** [mholt/archiver#204]

**Comment by mholt** [comment]
Hello, can you provide more details and explain why you need this?

**Comment by simar7** [comment]
Hello @mholt, I'd also like to +1 for this request. My use case would be an in memory tar file that I've read and hold a io.Reader/io.ReadCloser for. 

Currently Walk expects an archive name as the first argument https://github.com/mholt/archiver/blob/master/archiver.go#L214 it would be nice if it could take an io.Reader and read from it.

Does that make sense?

**Comment by frankh** [comment]
I'm also trying to use this library with archives held in memory, it would be great if either the `Archive`/`Unarchive` methods had equivalents that worked on Readers/Writers - of if `untarNext` was a public method

**Comment by markkuit** [comment]
Facing the same scenario where it would be really handy to walk over archives from memory.

**Comment by mholt** [comment]
Currently working this (along with a bunch of other issues) as I write v4 of this library.

**Comment by mholt** [comment]
#302 fixes this, as the core APIs have been completely rewritten and are entirely stream-based. Please try it out and let me know if you have any feedback!
