### ISSUE TITLE
Dep is missing - rebuild needed

### ISSUE THREAD

**Issue by iskrenpp** [mholt/archiver#206]
Been using your lz4 package but I started getting error today that "github.com/pierrec/lz4/v3" is missing. Please update the dep as needed to compile lz4.go

**Comment by loint** [comment]
package github.com/pierrec/lz4/v3 was dead

**Comment by palindrom615** [comment]
I have gone through this issue and in conclusion, nothing's wrong with both this repo and
https://github.com/pierrec/lz4/tree/v3 .

For some reason or other, `github.com/pierrec/lz4` is distributed both the old way(v2.x) and with go modules(v3.x). Thus, if your go version is below 1.14, you should set environment variable `GO111MODULE=on`  outside of directory with `go.mod` file.

like this:

```bash
env GO111MODULE=on go build github.com/you/yourapp
```

You can doublecheck this out: https://golang.org/cmd/go/#hdr-Module_support

**Comment by mholt** [comment]
Yes, until Go 1.14 (or whenever Go makes modules on by default), you need to set GO111MODULE=on.

**Comment by iskrenpp** [comment]
After trying setting this env var GO111MODULE=on, the issue still persisted for me. 
I deleted all local copies of any src or pkg in my GOPATH. The only fix that worked for me was after I ran at least once " go get" then I edited

> github.com/mholt/archiver/tarlz4.go
> github.com/mholt/archiver/lz4.go

and removed trailing /v3

then next 'go get' worked with no issues fetching all deps
