### ISSUE TITLE
Add support for zip bomb attack

### ISSUE THREAD

**Issue by mosheDO** [mholt/archiver#209]
## What would you like to have changed?

Support for [Zip BOMB](https://en.wikipedia.org/wiki/Zip_bomb)

## Why is this feature a useful, necessary, and/or important addition to this project?

A main security issue for extracting archives

**Comment by ilyapashuk** [comment]
please describe more precisely what you want.
are you want to sea some kind of protection for this atack or you want to have bom generator in this package?

**Comment by mosheDO** [comment]
I would like to have some kind of protection for this attack

**Comment by mholt** [comment]
In #302 I rewrote the entire library which will soon become v4. The new design is stream-based, and none of the core APIs write to the disk, so zip bomb isn't really relevant anymore.

If you're concerned about this, I suppose there are several forms to mitigate against, and that involves probably keeping track of writes as you write to disk.

**Comment by pombredanne** [comment]
but what about the CLI?

**Comment by mholt** [comment]
v4 doesn't have a CLI.
