### ISSUE TITLE
Question: How to use NameInArchive?

### ISSUE THREAD

**Issue by doronbehar** [mholt/archiver#214]
I'm writing a Go program that should be capable of printing contents of archives (it's called [Pistol](https://github.com/doronbehar/pistol)). My implementation is different somewhat in comparison to this project's `arc ls` though I'm still using the walker interface. The main difference is that I don't use a switch case for `f.Header.(type)`:

https://github.com/mholt/archiver/blob/44285f7ed244a1c0c1de72a5ac145f585f784a89/cmd/arc/main.go#L88-L97

I'm not very experienced in Go yet because it's only a hobby for me and I can't figure out how come `arc ls` prints full path via `h.Name` and how can I imitate that without such a switch.

I noticed that `arc ls` can't get the full path without knowing the type of the archive:

https://github.com/mholt/archiver/blob/44285f7ed244a1c0c1de72a5ac145f585f784a89/cmd/arc/main.go#L125-L130

So my question is, how to use `archiver.NameInArchive` to get the full path? I don't understand what's the meaning of `source` and `fpath` string arguments. And what should I put there in the context of a walker function. I tried all kinds of usages and I always got either an error or the basename of the file as always - as with `f.Name()`.

Help will be greatly appreciated.

**Comment by mholt** [comment]
Sorry I never replied to this... was really busy writing Caddy 2 at the time.

I've completely rewritten this package in #302, which will probably become v4. The file abstraction is similar, though, with a `NameInArchive` field. Hopefully the godoc is more descriptive/helpful there. Let me know if it's not, and if you have any further questions!
