### ISSUE TITLE
Not able to decompress a tar.gz file

### ISSUE THREAD

**Issue by jpninanjohn** [mholt/archiver#217]
## What steps did you take?
Tried to use Decompress to extract a `tar.gz` file

## What did you expect to happen, and what actually happened instead?
Expected:  Contents to be extracted succesfully
Actual: Failed with the message -> `format specified by source filename is not a recognized compression algorithm: tar.gz`

## How do you think this should be fixed?
https://github.com/mholt/archiver/blob/44285f7ed244a1c0c1de72a5ac145f585f784a89/targz.go#L26-L32

I noticed the CheckExt is checking for both extensions. But the file can have either one of them only. Think `&&` has to change to `||`

Also noticed this for a couple of other formats also. Eg. `tarbz2`

**Comment by mholt** [comment]
Oops, you might be right. Could you submit a PR?

**Comment by jpninanjohn** [comment]
Sure. I will fix the ones I can find that have the `&&`

**Comment by jpninanjohn** [comment]
I mistook another error and thought it was because of this. Existing code works fine. 

I do have a question though(might be a stupid one). For a file which is tarred and gzipped.. like `test.tar.gz`, should I use `Unarchive` or `DecompressFile`?

**Comment by mholt** [comment]
Use `Unarchive` :)
