### ISSUE TITLE
Support for avoiding overwrite upon opening archive

### ISSUE THREAD

**Issue by schollz** [mholt/archiver#22]
Hi @mholt, this is a great tool/library! 

I've found it useful to avoid overwriting files if they already exist when opening an archive to a folder. I'm wondering if you'd like to incorporate this as an option to your library? Here's my change: https://github.com/schollz/archiver/commit/8b912cafcb94be510e20d5c27ac803e3dd978de3. Of course, it would need to be amended so it can be toggled as optional.

**Comment by mholt** [comment]
Are you sure? I thought we already don't overwrite existing files...

**Comment by schollz** [comment]
Well, here is the behavior I'm getting. I have two files, and I archive only one of them. After archiving and then opening the archive in the same folder, the modified timestamp of the extracted file that came from the archive changes (from `15:52` to `15:53`). My thinking was that this should only happen if the archiver is overwriting, since the modification date is changed.

```
$ ls -l
total 8However
-rw-rw-r-- 1 zns zns  29 Feb 11 15:52 in_archive.txt
-rw-rw-r-- 1 zns zns  29 Feb 11 15:49 not_in_archive.txt
$ archiver make test.tar.bz2 in_archive.txt
$ archiver open test.tar.bz2               
$ ls -l
total 12
-rw-rw-r-- 1 zns zns  29 Feb 11 15:53 in_archive.txt
-rw-rw-r-- 1 zns zns  29 Feb 11 15:49 not_in_archive.txt
-rw-rw-r-- 1 zns zns 169 Feb 11 15:53 test.tar.bz2
```

The problem this creates, for me, is that when I re-archive the exact same file it creates a "different" archive because of the modified timestamp, and I'm using the md5 hashes to test differences in local/remote archives.

```
$ varchiver make test2.tar.bz2 in_archive.txt
$ md5sum *tar*                              
03eed92b4b87c4da5870fc50df9a48a9  test2.tar.bz2
7509268dc83ae1a630ffdaa54a1779d2  test.tar.bz2
```

**Comment by mholt** [comment]
Hmm, maybe we are now. I don't think that is intended. Want to submit a PR? :) Basically, return an error if a file already exists when extracting. Should just be a few lines. (Test welcome too if you're able!) I'm just super busy with stuff right now.

**Comment by schollz** [comment]
Sure! I'd be happy to!

**Comment by vishalb2308** [comment]
Is this change live? when I try to unarchive a file, it still overrides an existing one

**Comment by johnarok** [comment]
Not yet! Would you be willing to test your scenario using PR branch? https://github.com/mholt/archiver/pull/89

**Comment by mholt** [comment]
This feature is under way in #99
