### ISSUE TITLE
How to archive exclude Hidden files like .DS_Store

### ISSUE THREAD

**Issue by phpmaple** [mholt/archiver#220]

**Comment by Semi-Colin** [comment]
What do you mean by this? We can only help you if you give us the specific situation you are working with.

**Comment by jingyuLin1999** [comment]
A folder has many sub files. Packed with archive, he wants to exclude some sub files. I think that's what he meant. I'm in trouble with the same problem. I'm looking forward to your reply.

**Comment by mholt** [comment]
You can do this already, just populate your file list without the files you want to exclude: https://pkg.go.dev/github.com/mholt/archiver?tab=doc#Archive
