### ISSUE TITLE
Question: is split of tar archive possible?

### ISSUE THREAD

**Issue by mymtw** [mholt/archiver#227]
## What would you like to have changed?

Is it possible to create a tar archive split into blocks of a maximum size?
like [here](https://unix.stackexchange.com/questions/61774/create-a-tar-archive-split-into-blocks-of-a-maximum-size) advising it possible in unix as:
`tar cvzf - dir/ | split --bytes=200MB - sda1.backup.tar.gz.`

## Why is this feature a useful, necessary, and/or important addition to this project?

in our project we archiving pretty huge amount of files and it unsafe to store huge gb-tb size of file

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

-

## Please link to any relevant issues, pull requests, or other discussions.

as I'm guessing unix tar sends pipes to split like here: `tar cvzf - dir/ | split --bytes=200MB - sda1.backup.tar.gz.`
Is it possible to implement split feature here?

**Comment by 361442342** [comment]
@mholt 
is this need to be done?i want to join your project,so if this feature is necessary,i will take a try

**Comment by mholt** [comment]
Um, I haven't given it any thought yet, sorry -- been busy with Caddy stuff recently.

Anything is possible, but we just need a good proposal and then someone can implement it.

**Comment by cpach** [comment]
Splitting Zip archives would also be useful. Mainly because in Windows, there is no good native tool for splitting archives.

**Comment by mholt** [comment]
I believe the PR #302, which will soon become v4.0, may resolve this issue, because the new core APIs are entirely stream-oriented. So you'll provide a writer that, upon writing a number of bytes, switches files. I think something like that could work. If it doesn't, we can reopen this issue and discuss another solution.
