### ISSUE TITLE
No top level directory

### ISSUE THREAD

**Issue by mbyio** [mholt/archiver#228]
## What version of the package or command are you using?
3.2 on Linux

## What are you trying to do?
Create an archive while specifying files that are in a sub-directory.

## What steps did you take?
Here's a little script that'll produce an archive demonstrating the issue:

```sh
#!/bin/sh
set -e
cd $(mktemp -d)
mkdir subdir
touch subdir/hello
arc archive test.tar.gz subdir/hello
tar --list -f test.tar.gz
```

Here's a script showing what the normal `tar` command does:

```sh
#!/bin/sh
set -e
cd $(mktemp -d)
mkdir subdir
touch subdir/hello
tar -czf test.tar.gz subdir/hello
tar --list -f test.tar.gz
```

## What did you expect to happen, and what actually happened instead?
Because `arc` defaults to having `folder-safe` enabled, and because the files are in a sub-directory, they should be added to the archive with relative paths that include that sub-directory, or at least some sub-directory.

The first script above prints just `hello`, the second prints `subdir/hello`.

## How do you think this should be fixed?
Clarify in the docs that a top level directory is not always added and relative paths are stripped, or fix it so the paths aren't stripped and it behaves more like other tools (and has more functionality).

## Bonus: What do you use archiver for, and do you find it useful?
I like the simplified interface, and I like using it in Go code so I don't have to write anything custom to specify the archive format - this makes things more backwards compatible.

**Comment by mholt** [comment]
We can fix this with the command for v4.

**Comment by mholt** [comment]
As I don't have plans/time to make a command for v4 (unless sponsorships motivate it specifically), I'll close this issue; but I've labeled it with "command" so we can remember this if someone does end up contributing a command later. Thanks!
