### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by bkeroackdsc** [mholt/archiver#229]
## What would you like to have changed?
Consider adding `...WithContext()` functions/methods for long-running operations to allow cancellation by callers.

Example:

`ArchiveWithContext(ctx context.Context, sources []string, destination string) error`

This would allow cancellation without breaking API compatibility.

Internally, the implementation could (for example) check for context cancellation before/after each file is written (or read) to/from an archive and abort if the context is cancelled.

## Why is this feature a useful, necessary, and/or important addition to this project?
Archiving/unarchiving in particular can be long-running operations. It would be useful to allow a cancellation/timeout mechanism for callers.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
There is no alternative currently, other than performing the long-running operation in a separate goroutine and then ignoring or throwing away the results if the caller cancelled and is no longer interested.

**Comment by mholt** [comment]
Yeah, this would be good in a v4 rewrite.

**Comment by ilyapashuk** [comment]
and also some kind of progress monitoring can be useful, for example with callbacks.

**Comment by s3rj1k** [comment]
@mholt Any progress on that, also interested in context support.
@bkeroackdsc Care to share an example of work around?

**Comment by bkeroackdsc** [comment]
@s3rj1k the [wrapper pattern](https://play.golang.org/p/5IbpIN_1XH8), for example

**Comment by mholt** [comment]
Done in #302, the v4 rewrite.
