### ISSUE TITLE
New Core Team Member: @coolaj86

### ISSUE THREAD

**Issue by coolaj86** [mholt/archiver#235]
Hello, @weingart @jabgibson @johnarok @railsmechanic!

Please comment if you're still actively interested in helping maintain `arc` / `archiver`, so that I know I can tag you for reviews.

I had a conversation with @mholt that progressed from Twitter to the phone to me being added to the project to help out, so I wanted to introduce myself and summarize what we had talked about.

- Changes I'm interested:
    - adding a `version` subcommand
    - deploying to Github Releases with Goreleaser
    - adding `unz7` in CGo
        - this is an exception to the rule, as it uses CGo, and must stay behind an optional build tag
    - adding `webi` ([webinstall.dev/arc](https://webinstall.dev/arc)) as a "blessed" install method
- Other ways I want to contribute
    - review outstanding PRs, especially bugfixes and simple features - like https://github.com/mholt/archiver/pull/179

@mholt Has given me the green light to do this, and I'll be going through the normal review process with y'all to do it, but since I don't have any sort of working relationship with you as of yet, I just wanted to introduce myself and find out who I'm most likely to be engaging with.

Also, my first PR, which fixes the CI/CD pipeline (and makes it _much_ faster on Windows) is up at <https://github.com/mholt/archiver/pull/234>.

**Comment by mholt** [comment]
Thank you for helping out with this project, AJ! Hope you have fun with it. Hope others will be able to join in, too.
