### ISSUE TITLE
craft zip file for symlink testing

### ISSUE THREAD

**Issue by coolaj86** [mholt/archiver#247]
We need a special zip file that cannot be created with normal commandline tools. It requires crafting with an API. This should be possible with [`archive/zip#Writer`](https://golang.org/pkg/archive/zip/#Writer), for example.

We want a **double entry** of a file - the first being a symlink such that the second will be placed in an arbitrary location:

```txt
./goodfile.txt  "hello world"         (file)
./bad/file.txt  => ../../badfile.txt  (symlink)
./bad/file.txt  "Mwa-ha-ha"           (file)
./morefile.txt  "hello world"         (file)
```

This should go in [testdata/testarchives/evilarchives/](https://github.com/mholt/archiver/tree/master/testdata/testarchives/evilarchives) as `double-evil.zip` and `double-evil.tar` (if it is allowed).

See also https://github.com/mholt/archiver/issues/242#issuecomment-703086020

**Comment by kross9924** [comment]
can I work on this?

**Comment by coolaj86** [comment]
Assigned!

**Comment by kross9924** [comment]
@coolaj86 can you please elaborate on zip file structure.

**Comment by coolaj86** [comment]
@kross9924 Can you ask a more specific question? What about the file structure with 4 files as described above is unclear?

**Comment by kross9924** [comment]
Is this file structure ok  ?

                                                                                      double-evil.zip
                                                                                       /                   \
                                                                            badfile.txt                dir
                                                                                                               \
                                                                                                                  subdir     
                                                                                                             /         \                 \
                                                                                                  goodfile.txt   morefile.txt   bad
                                                                                                                                              \
                                                                                                                                           file.txt

**Comment by kross9924** [comment]
Is this structure correct>

double-evil.zip
1.badfile.txt  2.dir
                       2.1 subdir
                          2.1.1 goodfile.txt     2.1.2 morefile.txt     2.1.3 bad
                                                                                           2.1.3.1 file.txt

**Comment by coolaj86** [comment]
Use code fences and tables:

~~~md
```bash
lsd --tree .
```

```txt
./
├── bad/
│  └── file.txt
├── goodfile.txt
└── morefile.txt
```

| filepath | type | contents |  link |
|  ------- | ---- | --------- | ---- |
| ./goodfile.txt | file | "hello world"  | N/A |
| ./bad/file.txt | symlink | N/A | ../../badfile.txt |
| ./bad/file.txt | file | "Mwa-ha-ha"  | N/A |
| ./morefile.txt | file | "hello world"  | N/A |
~~~

The point is that you can't actually create such a malicious file structure on disk:

```bash
lsd --tree .
```

```txt
./
├── bad/
│  └── file.txt
├── goodfile.txt
└── morefile.txt
```

`bad/file.txt` can only be either a file, or a link. It can't be both. However, zip and tar file indexes you can manipulate.

The directory structure in the zip file table should be exactly this:

| filepath | type | contents |  link |
|  ------- | ---- | --------- | ---- |
| ./goodfile.txt | file | "hello world"  | N/A |
| ./bad/file.txt | symlink | N/A | ../../badfile.txt |
| ./bad/file.txt | file | "Mwa-ha-ha"  | N/A |
| ./morefile.txt | file | "hello world"  | N/A |

**Comment by coolaj86** [comment]
@kross9924 Are you still working on this?

**Comment by kross9924** [comment]
Yes I am working

**Comment by kross9924** [comment]
Opening a symlink file inside program is dereferencing it, so how can I add it in zip file?
@coolaj86 Please help

**Comment by coolaj86** [comment]
Don’t try to use real files.

Use the zip and tar writer API with byte strings and header objects.

That said, `lstat` does a link stat without following the link.

**Comment by kross9924** [comment]
I am unable to figure out even after reading documentation several time.

How can I insert symlink into zip/tar file using writer API ?

@coolaj86 Please help.

**Comment by coolaj86** [comment]
Check out the golang test: https://golang.org/src/archive/zip/writer_test.go

Search "symlink" on that page.

**Comment by kross9924** [comment]
In tar file there is double entry of bad/file.txt 
I guess that's fine.
created a pull request
Thank you.
