### ISSUE TITLE
Failed to decompress the file containing garbled code in MAC

### ISSUE THREAD

**Issue by smile0304** [mholt/archiver#261]
This file is a zip file compressed under Windows 10 (Simplified Chinese). I copied it to Mac and decompressed it. The following error occurred：
`reading file in zip archive: /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: making directory: mkdir /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: illegal byte sequence`

My test sample code:
```
func TestUnArchiver(t *testing.T) {

	convey.Convey("测试乱码文件解压", t, func() {
		basePath := "/Users/tt/test_demo"
		fileName := "test.zip"

		sourPath := path.Join(basePath, fileName)
		randomPath, err := uuid.GenerateUUID()

		convey.So(err, convey.ShouldBeEmpty)

		resPath := path.Join(basePath, randomPath)

		_, err = CheckAndMkDirPath(resPath)
		convey.So(err, convey.ShouldBeEmpty)

		files, err := Decompression(sourPath, resPath)
		if err != nil {
			fmt.Println(err.Error())
		}
		convey.So(len(files), convey.ShouldBeGreaterThan, 0)
		convey.So(err, convey.ShouldBeEmpty)
	})

}
```

Decompression function:
```
func Decompression(source, destination string) (files []string, err error) {
	err = archiver.Unarchive(source, destination)
	if err != nil {
		return files, err
	}
	return GetAllFiles(destination)
}
```

I debugged this code，in `/Users/xx/go/pkg/mod/github.com/mholt/archiver/v3@v3.3.0/zip.go` file 188 line

Archiver will splice the path and the file name in the compressed package, and then create a folder. However, the actual stitched path is a piece of garbled code and cannot be created normally

![image](https://user-images.githubusercontent.com/20963266/99037576-e9b68900-25be-11eb-933d-97b27a79025d.png)

My test file:
[test.zip](https://github.com/mholt/archiver/files/5535186/test.zip)

Looking forward to your reply

## What version of the package or command are you using?

go version go1.14.6 darwin/amd64
github.com/mholt/archiver/v3 v3.3.0

## What are you trying to do?

This file is a zip file compressed under Windows 10 (Simplified Chinese). I copied it to Mac and decompressed it. The following error occurred：
`reading file in zip archive: /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: making directory: mkdir /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: illegal byte sequence`

## What steps did you take?

f the file is a compressed package compressed under Mac, it will be OK

## What did you expect to happen, and what actually happened instead?

He should have extracted the files, but there was a mistake，
error:
`reading file in zip archive: /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: making directory: mkdir /Users/xx/test_demo/d9915c63-812c-6c9e-92fb-66dd7645dc0b/��������: illegal byte sequence`

## How do you think this should be fixed?

We can talk about renaming files that cannot be decompressed

## Bonus: What do you use archiver for, and do you find it useful?

Very Good！！

**Comment by xwinie** [comment]
最后怎么解决的呢？
