### ISSUE TITLE
How to set default options?

### ISSUE THREAD

**Issue by danez** [mholt/archiver#264]
I would like to set `StripComponents = 1` for all types which support it and use `archiver.Unarchive()`.

I cannot figure out how to change the default options though. First I tried doing `archiver.DefaultTar.StripComponents = 1`, but I see now that `Unarchive()` is always creating a new instance.

Is there a way to do it?

**Comment by Or-Geva** [comment]
I have the same issue with `OverwriteExisting` which by default is false.

**Comment by mholt** [comment]
This can be done with the v4 rewrite introduced in #302.
