### ISSUE TITLE
Readme incorrectly mentions not mitigating zip-slip attacks

### ISSUE THREAD

**Issue by Jacalz** [mholt/archiver#271]
The README does specifically specify that this package doesn’t try to prevent zip-slip attacks due to various cross-platform issues and so on. However, looking at the current code and the various releases that have been made in the last couple of months, it looks to not be true any more. https://github.com/mholt/archiver/commit/8217ed3a206c0473b4ec1aff51375b398838073a

**Comment by coolaj86** [comment]
There's still an issue that we need to resolve. We need to defer symbolic links - like tar does. The existing mechanism can still be defeated.

**Comment by Jacalz** [comment]
Ah, I see. Thank you for your explanation. I guess that https://github.com/mholt/archiver/pull/269 solves that issue? If so, it would be great to see that implemented :)

**Comment by mholt** [comment]
Closing, as zip-slip isn't relevant in v4 (as it does not write to disk) -- that may change if/when the command is reimplemented around the v4 APIs, but we can deal with that then if that's the case.
