### ISSUE TITLE
archiver.Extract with archiver.Walk not support package with dir

### ISSUE THREAD

**Issue by DeJoker** [mholt/archiver#275]
## What version of the package or command are you using?
v3.5.0  25e050d

## What are you trying to do?

I try a zip package with gbk encoding(not utf8), somehow archiver.Unarchive not unpack all files, because the nonutf8 name is same,so it with return err  "file already exists: xxx".
so, I try another way to extract it.

```go
i := 1
renameWalk := func(f archiver.File) error {
    extracePath := filepath.Join(dest, strconv.Itoa(i))
    os.MkdirAll(extracePath, os.ModePerm)
    
    err := archiver.Extract(src, f.Name(), dest)
    if err != nil {
	    logs.Error(err)
    }
    i++
    return nil
}

return archiver.Walk(src, renameWalk)
```

but it get nothing, the zip package is a dir contains the ppt file,just like this:
```
aa.zip
└──a_dir/
        └── fsf.mp3
```

when I walk this package, then f.Name() just return fsf.mp3   I check the raw struct of  archiver.File in func(f archiver.File). There is no path info in this struct, so I can make it right in this version.

## What did you expect to happen, and what actually happened instead?
so, I need a f.Name() with dir in this package.

## How do you think this should be fixed?
add the dir position to the function Name(), or add a function to abs path to the file.

## Bonus: What do you use archiver for, and do you find it useful?
In Windows unarchive the file, most rar and zip.

**Comment by mholt** [comment]
I rewrote this package in #302, and it gives the ability to archive and extract precisely how you want to, including with full path, so I think this is resolved. :)
