### ISSUE TITLE
Exclude files by pattern

### ISSUE THREAD

**Issue by atsikham** [mholt/archiver#279]
## What would you like to have changed?

Currently there is only an ability (at least it's documented so) to specify files/directories to add into archive. Exclude some files from specified directories by pattern would be helpful.

## Why is this feature a useful, necessary, and/or important addition to this project?

My use-case is filtering logs with *.log extension out, but I'm sure there are a lot of other ones.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Make a copy of the directory to compress, remove unnecessary files, compress.

**Comment by nononsensecode** [comment]
There is also one use-case, when we want to exclude the .git directory

**Comment by mholt** [comment]
We can probably find a way to work this into #302, which is a complete rewrite of this package and destined to become v4.

**Comment by mholt** [comment]
One option in v4 is to use `FilesFromDisk()` and then simply remove the files you don't want from the resulting slice. :man_shrugging: 

We can reopen this if needed, but I think that'll work fine unless there's a use case not covered sufficiently by that solution.

**Comment by NotGabry** [comment]
is there any way to exclude the file directly from `FilesFromDisk()` beacause when (in linux) archiver tries to read a file that is locked by another program it crashes, an idea cloud be adding `false` to the path of file like
```golang
files, err := archiver.FilesFromDisk(nil, map[string]string{
	"/home/randuser/folder/randfile.txt.lck": false,
	"/home/randuser/folder": "folder"
})
```

**Comment by mholt** [comment]
But `false` is not a string. And `"false"` could be a filename, so I don't think that will do.

> beacause when (in linux) archiver tries to read a file that is locked by another program it crashes

Is that a Windows-thing? What is the output? Archiver shouldn't _crash_ (panic) but if you get an error, that's understandable.
