### ISSUE TITLE
Non-UNIX compatibility

### ISSUE THREAD

**Issue by rafaeljusto** [mholt/archiver#28]
I was looking at the `tarFile` function and saw a harcoded "/" in it:
https://github.com/mholt/archiver/blob/master/tar.go#L146

Shouldn't we use [os.PathSeparator](https://golang.org/pkg/os/#pkg-constants) instead of "/"? If necessary I can send a PR.

Ignore/Close this issue if there's no problem on using this character as path separator in Windows environments. I'm also a UNIX user. :smile:

**Comment by mholt** [comment]
No, I think tar files require "/" as path separators. A forward slash is always used, even on Windows.
