### ISSUE TITLE
Is there a way NOT to preserve file attributes?

### ISSUE THREAD

**Issue by ivanduka** [mholt/archiver#280]
Hi, thanks for creating this tool!

I use it for database archiving, i.e. I generate SQL of a database and then archive it. In case there were no changes in the DB, the content of those files is the same (md5 hash is the same), but the creation, modification, and access time stamps are different. When I use archiver to create an archive, the archive checksum is different of course because of those extended attributes of files that are within it.

Is there a way to disable preserving those attributes while creating archives? Obviously, all 3 would be set to the moment of extraction of such archive.

**Comment by carolynvs** [comment]
I am really interested in this as well and am happy to submit a pull request if this is a feature you are interested in? Either separate options to let them control the file header info more: mode, uid, gid, uname, etc or something like "Deterministic" that just takes care of everything that needs to be omitted for you. Something similar to `gzip --no-name`.

**Comment by mholt** [comment]
I've been a bit overwhelmed lately... Would anyone like to take up maintenance of this project?

**Comment by mholt** [comment]
Is this wanted for the command line tool or the core library?

Because the core library has been completely rewritten in #302 and probably allows you to do what you want. The new CLI could certainly honor that.

**Comment by mholt** [comment]
Ok, I made a pull request that _should_ do what you need, but only you can really determine if it works for your use case. @carolynvs @vdice @ivanduka Can you please give the branch in #280 a try?

**Comment by mholt** [comment]
Done in #280 - thanks
