### ISSUE TITLE
Is it possible to unrar a file from memory rather than having to write it to disk and pass it a file name?

### ISSUE THREAD

**Issue by mcastrogg** [mholt/archiver#282]
Hello, a bit new to go so apologies if i'm missing something obvious here. But is there a simple way to pass an ioReader containing a .rar to one of the functions and then init the Rar from the ioReader rather than having to pass it the file path? 

Thanks.

**Comment by mholt** [comment]
There is now! That is what #302 does, which is a complete rewrite of this package and will become v4.
