### ISSUE TITLE
Seeking new maintainer(s)

### ISSUE THREAD

**Issue by mholt** [mholt/archiver#283]
This library continues to be popular, but I haven't been able to allocate the time necessary to work on it. Like other of my open source projects, it has gone beyond the realm of "fun weekend project that only I use" to "numerous real world use cases relying on it" -- and my sponsorships are currently swaying me to work on Caddy projects.

I'm opening this up to others who would like to volunteer to maintain this. I don't mean to merely submit a PR, but I mean to review PRs, triage issues, and in general to facilitate the ongoing development of the project over a long period of time. I'll be mostly hands-off -- unless you want another opinion on things or if you want some technical vision, but I just don't have the time to devote to development of this right now.

Maintainership is not a glorious role, but it's great experience and it can be fun. It is also a necessity for _someone_ to do, if you use or rely on this library. That could be you! :)

Who would like to commit to this role? Could probably add a few maintainers.

**Comment by coolaj86** [comment]
I backed off while you were creating the new version and haven't really checked in in a while.

I'm also spread thin, but I'm willing to help.

**Comment by mholt** [comment]
I found a new burst of energy for this repo, so I'm giving it some love again, mainly with #302.

Thanks for helping, AJ!  :+1:
