### ISSUE TITLE
Is there a performance test report

### ISSUE THREAD

**Issue by rockli0724** [mholt/archiver#288]
Hi, thanks for creating this tool!
    I want to compress some large files and want to investigate the performance?
just like gin's benckmark data
[https://github.com/gin-gonic/gin/blob/master/BENCHMARKS.md](https://github.com/gin-gonic/gin/blob/master/BENCHMARKS.md)
![gin-benchmark](https://user-images.githubusercontent.com/13429774/125230594-a6f2af80-e30b-11eb-867c-a86b0066d069.png)
   thank you very much！！

**Comment by mholt** [comment]
I don't know of one. Haven't really put much effort into optimizing this lib. You might be interested, instead, in a comparison of performance of the underlying compression libraries, for example: https://github.com/klauspost/compress
