### ISSUE TITLE
extract is broken when extracting folders from zip (only creates folders)

### ISSUE THREAD

**Issue by fiws** [mholt/archiver#289]
## What version of the package or command are you using?

arc v3.5.0 25e050dbb4e3c591402916201098241bb661a2f7 (2020-10-30T03:27:58Z)

## What are you trying to do?

Extracting a single directory from a zip file.

### repro
```
wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10_openj9-0.26.0/OpenJDK8U-jre_x64_windows_openj9_8u292b10_openj9-0.26.0.zip
arc extract OpenJDK8U-jre_x64_windows_openj9_8u292b10_openj9-0.26.0.zip jdk8u292-b10-jre extracted

# note that there are no files, only directories
ls -l extracted/jdk8u292-b10-jre/bin
```
### ls output
```
drwxr-xr-x  3 root root 4096 Jul 25 13:50 JAWTAccessBridge-64.dll
drwxr-xr-x  3 root root 4096 Jul 25 13:50 JavaAccessBridge-64.dll
drwxr-xr-x  3 root root 4096 Jul 25 13:50 WindowsAccessBridge-64.dll
drwxr-xr-x  3 root root 4096 Jul 25 13:50 awt.dll
[...]
```

## What did you expect to happen, and what actually happened instead?

Should properly extract directory from archive, instead only directories where created. Everything that should have been files ended up as empty directories. 
I don't know if this is limited to the zip file is used but it works if i extract the whole archive.

## How do you think this should be fixed?

Not sure.

## Please link to any related issues, pull requests, and/or discussion

Found nothing

## Bonus: What do you use archiver for, and do you find it useful?

OpenJDK extraction, modpack extraction for https://github.com/minepkg/minepkg

**Comment by mholt** [comment]
This is probably (?) not relevant in v4, but if it turns out to still be a problem, let me know and we can re-open this.
