### ISSUE TITLE
decompression rar file exception

### ISSUE THREAD

**Issue by yanzhirong** [mholt/archiver#292]
## What version of the package or command are you using?
v3.1.1

## What are you trying to do?
decompression rar file

## What steps did you take?
err := archiver.Unarchive(source, destination)

## What did you expect to happen, and what actually happened instead?
 expect to happen：decompression success
 actually happened instead：some rar file decompression error
error log：reading file in rar archive: D:\\test\\data\\XXXXX.exe: writing file: rardecode: invalid filter

## How do you think this should be fixed?
file：github.com\nwaples\rardecode\decode_reader.go
function：queueFilter
#################################################
for _, fb := range d.filters {
		if f.offset < fb.offset {
			// filter block must not start before previous filter
			return errInvalidFilter
		}
		f.offset -= fb.offset
	}
#################################################

## Please link to any related issues, pull requests, and/or discussion
null

## Bonus: What do you use archiver for, and do you find it useful?
use archiver for decompression rar/zip/tar.gz file

**Comment by mholt** [comment]
Thanks, but probably needs to be reported and fixed upstream in the rardecode repository: https://github.com/nwaples/rardecode/issues
