### ISSUE TITLE
Add Github Actions support

### ISSUE THREAD

**Issue by iotanbo** [mholt/archiver#297]
## What would you like to have changed?
Add Github Actions for CI.

## Why is this feature a useful, necessary, and/or important addition to this project?
It's a powerful and relatively simple CI solution comparing to others.

Before creating PR, I'd like to discuss the following:

1. Changes on which branches should trigger build and running tests (I suggest all)?
2. Should there be 3 separate badges for MacOS, Ubuntu and Windows in README or a single badge for all OSs (I suggest separate)?
3. Should Azure Pipelines be removed in the same PR (I suggest no)?

**Comment by mholt** [comment]
Thanks for the PR -- yeah, I think those are all fine, except I'd like to remove Azure. Thanks for doing that!
