### ISSUE TITLE
If rar file has child same name dir,what can i do

### ISSUE THREAD

**Issue by caiziqi33** [mholt/archiver#308]
## What did you expect to happen, and what actually happened instead?

Unarchive is error：/xx/xx/xx/xx/xxxx.rar reading file in rar archive: /xx/xx/xx/xx//xxxx: creating new file: open  /xx/xx/xx/xx//xxxx: is a directory

**Comment by mholt** [comment]
Unfortunately there's not enough information here to help you :( Please don't skip/remove questions.
