### ISSUE TITLE
v4 archiver.Zip.Extract can not read all bytes

### ISSUE THREAD

**Issue by pashifika** [mholt/archiver#309]
## What version of the package or command are you using?

v4
0448c6dfcbabd47dc669263b1d1763f8afb4093b + https://github.com/pashifika/archiver/commits/master

## What are you trying to do?

use Virtual file systems to get all image file bytes.

My code:
![image](https://user-images.githubusercontent.com/11887000/149137522-e3d00c79-5dd3-4df2-9062-106251d30fa8.png)

I want to read all bytes from each file, but the bytes I read are incomplete... A large portion is empty, such as the last 10 bytes seen in the image.
![image](https://user-images.githubusercontent.com/11887000/149136865-6582a447-6070-4c12-b054-0298e1a5b586.png)

![image](https://user-images.githubusercontent.com/11887000/149136369-d698c641-3390-44aa-bb5e-7479d74a2795.png)

![image](https://user-images.githubusercontent.com/11887000/149136680-1c90ab34-db9a-4f25-8092-24c4e8020ce0.png)

![image](https://user-images.githubusercontent.com/11887000/149136717-72f9a5ec-c328-4162-94ec-db9c9ab923ce.png)

**Comment by pashifika** [comment]
@mholt 
Can you fix this bug? I tried it myself, but I couldn't get a clue, your code is too complicated.

**Comment by mholt** [comment]
I would like to reproduce the bug, but I can't execute screenshots.

If you eliminate the concurrency, do you get the results you expect?

**Comment by pashifika** [comment]
@mholt 
```go
// Package issues309
package main

import (
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"strings"

	"github.com/mholt/archiver/v4"
)

func main() {
	filePath := "you full path/images.zip"
	fsys, err := archiver.FileSystem(filePath)
	if err != nil {
		panic(err)
	}

	var archivers []archiver.File
	extensions := []string{".jpg", ".jpeg"}
	err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch path {
			case ".git":
				return fs.SkipDir
			default:
				return nil
			}
		} else {
			// Image file filter
			for _, ext := range extensions {
				if ext == filepath.Ext(strings.ToLower(path)) {
					var info fs.FileInfo
					info, err = d.Info()
					if err != nil {
						return err
					}
					archivers = append(archivers, archiver.File{
						FileInfo:      info,
						NameInArchive: path,
						Open: func() (io.ReadCloser, error) {
							return nil, nil
						},
					})
				}
			}
		}
		return nil
	})

	for _, file := range archivers {
		af, err := fsys.Open(file.NameInArchive)
		if err != nil {
			panic(err)
		}
		info, err := af.Stat()
		if err != nil {
			panic(err)
		}

		bytes := make([]byte, info.Size())
		_, err = af.Read(bytes)
		if err != nil {
			panic(err)
		}
		last10bytes := bytes[info.Size()-10:]
		fmt.Println(last10bytes)
	}
}
```

this is a bug zip file, you can see that the last 10bytes of the first file is empty
[images.zip](https://github.com/mholt/archiver/files/7858740/images.zip)

OS: Windows 11 Pro for Workstations 22000.376
Go: go version go1.17.6 windows/amd64

```
C:\Users\Pashifika\AppData\Local\Temp\GoLand\___1go_build_github_com_gen2brain_go_unarr_example_issues309.exe
[0 0 0 0 0 0 0 0 0 0]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
[0 0 73 69 78 68 174 66 96 130]
```

**Comment by mholt** [comment]
@pashifika Thanks for distilling that down. Now I see an obvious potential bug in your code. `_, err = af.Read(bytes)` is not guaranteed to read any or all bytes. Make sure you read the docs for `io.Reader`: https://pkg.go.dev/io#Reader

You may want to use `io.Copy()` or `io.ReadFull()` instead.

**Comment by pashifika** [comment]
@mholt 

I'm sorry to bother you for many times. Is it a bug that the same file appears twice when reading rar file or do I need to write filters to eliminate it?
![image](https://user-images.githubusercontent.com/11887000/149251169-81fbe90f-0ac3-4b5e-b00a-38107f4bb908.png)

**Comment by pashifika** [comment]
@mholt 
WinRAR 6.0.2(64 bit)
[images.rar.zip(Please rename to images.rar)](https://github.com/mholt/archiver/files/7859453/images.rar.zip)

thanks.

**Comment by mholt** [comment]
I _assume_ the contents are flat within the `images` subfolder?

```
$ go run main.go 
2022/01/13 10:55:54 images/1034560.jpg
2022/01/13 10:55:54 images/abc1.jpg
2022/01/13 10:55:54 images/abc10.jpg
2022/01/13 10:55:54 images/abc11.jpg
2022/01/13 10:55:54 images/abc12.jpg
2022/01/13 10:55:54 images/abc2.jpg
2022/01/13 10:55:54 images/abc3.jpg
2022/01/13 10:55:54 images/abc4.jpg
2022/01/13 10:55:54 images/abc5.jpg
2022/01/13 10:55:54 images/abc6.jpg
2022/01/13 10:55:54 images/abc7.jpg
2022/01/13 10:55:54 images/abc8.jpg
2022/01/13 10:55:54 images/abc9.jpg
2022/01/13 10:55:54 images
```

If so, it works for me. There must be a bug in your code.

```go
f, err := os.Open("/home/matt/Downloads/images.rar")
if err != nil {
	log.Fatal(err)
}
defer f.Close()

err = archiver.Rar{}.Extract(context.Background(), f, nil, func(_ context.Context, f archiver.File) error {
	log.Println(f.NameInArchive)
	return nil
})
if err != nil {
	log.Fatal(err)
}
```
