### ISSUE TITLE
v4 rar file bug in Virtual file systems

### ISSUE THREAD

**Issue by pashifika** [mholt/archiver#310]
## What version of the package or command are you using?

v4.0.0-alpha.2

## What are you trying to do?

1. Extract rar file

no bug code:
```go
f, err := os.Open("/home/matt/Downloads/images.rar")
if err != nil {
	log.Fatal(err)
}
defer f.Close()

err = archiver.Rar{}.Extract(context.Background(), f, nil, func(_ context.Context, f archiver.File) error {
	log.Println(f.NameInArchive)
	return nil
})
if err != nil {
	log.Fatal(err)
}
```

duplicate file bug:
```go
	filePath := "./images.rar"
	fsys, err := archiver.FileSystem(filePath)
	if err != nil {
		panic(err)
	}
	err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		fmt.Println(path)
		return nil
	})
	if err != nil {
		panic(err)
	}
```

bug output:
```
.
images/1034560.jpg
images/abc1.jpg
images/abc10.jpg
images/abc11.jpg
images/abc12.jpg
images/abc2.jpg
images/abc3.jpg
images/abc4.jpg
images/abc5.jpg
images/abc6.jpg
images/abc7.jpg
images/abc8.jpg
images/abc9.jpg
images
images/images/1034560.jpg
images/images/abc1.jpg
images/images/abc10.jpg
images/images/abc11.jpg
images/images/abc12.jpg
images/images/abc2.jpg
images/images/abc3.jpg
images/images/abc4.jpg
images/images/abc5.jpg
images/images/abc6.jpg
images/images/abc7.jpg
images/images/abc8.jpg
images/images/abc9.jpg
```

Windows and MAC can reproduce it:
![image](https://user-images.githubusercontent.com/11887000/149427974-e1bcd719-6eeb-48cd-b48f-c0c136123bd7.png)
![image](https://user-images.githubusercontent.com/11887000/149427955-7c606add-9d1b-4b9b-af74-fe9ba4f71356.png)

**Comment by mholt** [comment]
Thank you for this, will take a closer look soon. Am just heading out for the evening.

**Comment by mholt** [comment]
I was able to confirm the bug, I think I have a hunch as to what is causing it.

Also, I appreciate the minimal use case to reproduce the bug, it made that very easy this time. Thanks.

**Comment by mholt** [comment]
It's weird, for some reason your .rar file lists the files first (depth-first) instead of the folders containing them (breadth-first).

**Comment by pashifika** [comment]
I think the easiest way is to check for duplicates with map?

**Comment by mholt** [comment]
I thought of that, but I think it's better to compare file prefixes when traversing, to make sure we're not going into subfolders when we shouldn't be. This should avoid expending memory.

**Comment by mholt** [comment]
@pashifika I pushed a couple of commits that should resolve the issue. One eliminates the weird repeated directory name ("images/images/...") and another fixes the listing of directories when archives are created depth-first.

Thanks again for the reports. Please continue to paste code as text instead of screenshots in the future :)
