### ISSUE TITLE
Windows path handling (tar.gz, probably others, too)

### ISSUE THREAD

**Issue by seizmo** [mholt/archiver#313]
## What version of the package or command are you using?

v4 lastest (d777df9)

## What are you trying to do?
Create a tar.gz file under windows.

## What steps did you take?
```	
       files, err := archiver.FilesFromDisk(nil, map[string]string{
		".\res\test\tenant_files\tenant_1": "", // contents added recursively
	})
	if err != nil {
		return err
	}

	archiveDir, err := job.ArchiveDirectory(true)

	// create the output file we'll write to
	out, err := os.Create(filepath.Join(archiveDir, "files.tar.gz"))
	if err != nil {
		return err
	}
	defer out.Close()

	// we can use the CompressedArchive type to gzip a tarball
	// (compression is not required; you could use Tar directly)
	format := archiver.CompressedArchive{
		Compression: archiver.Gz{},
		Archival:    archiver.Tar{},
	}

	// create the archive
	err = format.Archive(context.Background(), out, files)
	if err != nil {
		return err
	}
```

## What did you expect to happen, and what actually happened instead?
Opening the file with 7-zip should extract to the same directory structure of the original files

## How do you think this should be fixed?

https://github.com/mholt/archiver/blob/master/archiver.go should probably use filepath instead of path since path only supports slashes and no backslashes

## Bonus: What do you use archiver for, and do you find it useful?
Just got started but really like the API (and the author, thanks for Caddy!!!) :)

**Comment by mholt** [comment]
Thanks; I don't have Windows to test this. Can you give more information? What exactly is broken? What is in the created archive?

**Comment by seizmo** [comment]
The problem seems to be that the Windows backlash is not removed/replaced with slashes but included in the archive entries in escaped form:
```
tenant_1
tenant_1/\\1
tenant_1/\\1\\file-example_PDF_1MB.pdf
tenant_1/\\2
tenant_1/\\2\\file-example_PDF_500_kB.pdf
tenant_1/\\3
tenant_1/\\3\\file-sample_150kB.pdf
```
This is what I get if I unpack that file on Linux (using `tar xzvf`)

**Comment by mholt** [comment]
Ah, indeed, `path.Join()` calls `path.Clean()` which does NOT call `ToSlash()`. Only `filepath.Join()` calls `filepath.Clean()` which DOES call `FromSlash()`. :roll_eyes:  I get why, but that was a silly oversight on my part.

Can you test what I push to a branch? (Until I have a chance to write actual automated tests, heh. Just been busy lately.)

**Comment by seizmo** [comment]
I changed the two lines and it worked for me on Windows with Go 1.18. 7zip on windows now also opens and extracts the archive to a Windows folder with correctly named files. 

Thanks a lot!

**Comment by mholt** [comment]
Great, thanks for confirming!
