### ISSUE TITLE
Add compressed file to existent archive file

### ISSUE THREAD

**Issue by luxcgo** [mholt/archiver#321]
## What would you like to have changed?
I wonder if it supports to add a new compressed file to for example a bz2 file that already exists.

## Why is this feature a useful, necessary, and/or important addition to this project?
Don't want to create a new bz2 file.

## Please link to any relevant issues, pull requests, or other discussions.
Similar request: https://unix.stackexchange.com/questions/13093/how-to-add-update-a-file-to-an-existing-tar-gz-archive

**Comment by mholt** [comment]
You want to add a .bz2 file to an existing archive file?

Or you want to add an existing file to an archive file compressed with bz2?

I'm confused.

But if you want to add a file to an existing _compressed_ tar file (like tar.gz) then you can't really do that without creating a new one. (I actually found the same post on Unix Stack Exchange when I was writing this lib.)

Closing, as I don't think this is actionable without more/new information.
