### ISSUE TITLE
Seek() in archive file

### ISSUE THREAD

**Issue by nicola-spb** [mholt/archiver#323]
Hello,

When i walking in archive I have fs.File (without Seek()). How can I get ReadSeeker interface of it?
```
fsys, err := archiver.FileSystem(sourcePath)
if err != nil {
	return nil, err
}
	
err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
	if err != nil {
		return err
	}

	f, err := fsys.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	
	frs := f.(io.ReadSeeker)  // Error
}
```

Thanks

**Comment by mholt** [comment]
I don't think the underlying archive format implementations (tar, zip, etc) give us `Seek()`, sorry.

It does seem like that should be able to work when dealing with regular files on disk, but this might be a feature request more for the standard library (or whatever package implements the underlying archive format).

Will close this, but feel free to continue discussion. I could very well be wrong.

**Comment by oliverpool** [comment]
I tried to implement a caddy module after the merge of https://github.com/caddyserver/caddy/pull/4909 but it panics because of this:

```
http.stdlib	http: panic serving 127.0.0.1:46708: interface conversion: archiver.extractedFile is not io.ReadSeeker: missing method Seek
```

**Comment by oliverpool** [comment]
https://github.com/nlepage/go-tarfs works fine ! (since https://github.com/nlepage/go-tarfs/pull/4)

**Comment by oliverpool** [comment]
I just realized, that it reads the whole file in memory: https://github.com/nlepage/go-tarfs/blob/bec76bb13b0a3be9e1bf8bb03141a6d26ce91902/fs.go#L39-L44 ...

**Comment by mholt** [comment]
@oliverpool 

> I tried to implement a caddy module after the merge of https://github.com/caddyserver/caddy/pull/4909 but it panics because of this:

Gah, I forgot about that.

> I just realized, that it reads the whole file in memory: [nlepage/go-tarfs@bec76bb/fs.go#L39-L44](https://github.com/nlepage/go-tarfs/blob/bec76bb13b0a3be9e1bf8bb03141a6d26ce91902/fs.go#L39-L44) ...

Yikes, haha. That probably won't do for production use. Thanks for experimenting with it!!
