### ISSUE TITLE
messy code with chinese file name

### ISSUE THREAD

**Issue by chrislearn** [mholt/archiver#33]
When there is file with chinese name, the unzipped filename is messy code.

![image](https://cloud.githubusercontent.com/assets/5874864/26238289/057f512c-3cab-11e7-9407-63a000b49114.png)

I use windows 10 pro. go 1.8.1 64bit version

**Comment by halfcrazy** [comment]
If you are using a Chinese window system, the file name is in GBK encoding. If you want zip to support this case, you may set zip header's flag bit 11. `header.Flags = 1 << 11` 
Or convert your filename to utf-8.

ref: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

D.2 If general purpose bit 11 is unset, the file name and comment should conform 
to the original ZIP character encoding.  If general purpose bit 11 is set, the 
filename and comment must support The Unicode Standard, Version 4.1.0 or 
greater using the character encoding form defined by the UTF-8 storage 
specification.  The Unicode Standard is published by the The Unicode
Consortium (www.unicode.org).  UTF-8 encoded data stored within ZIP files 
is expected to not include a byte order mark (BOM).
