### ISSUE TITLE
Using FilesFromDisk() for compressing files to root of archive

### ISSUE THREAD

**Issue by nicola-spb** [mholt/archiver#331]
## What would you like to have changed?
I wanna use archiver.FilesFromDisk for archiving files from folder to root of archive like this:
```
files, err := archiver.FilesFromDisk(nil, map[string]string{
	"/path/on/disk/folder/*":    "", // contents added recursively to root of archive without "folder"
})
```

## Why is this feature a useful, necessary, and/or important addition to this project?
I think it is useful feature.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Without this feature I need to write:
```
fileNames := make(map[string]string)
err := filepath.Walk(sourceDir, func(path string, info os.FileInfo, err error) error {
	if err != nil {
		return err
	}

	// skip root directory
	if path == sourceDir {
		return nil
	}

	fileNames[path] = ""
	return nil
})

if err != nil {
	return err
}

// map files on disk to their paths in the archive
files, err := archiver.FilesFromDisk(nil, fileNames)
```

**Comment by mholt** [comment]
Thanks for the request. Just to be sure I understand, can you provide a sample directory tree and the expected names in the archives? Basically the expected inputs and outputs.

**Comment by nicola-spb** [comment]
Example. I have folder:

```
/path/on/disk/folder/file1.txt
/path/on/disk/folder/file2.txt
/path/on/disk/folder/file3.txt
/path/on/disk/folder/subfolder/file4.txt
```

And I wanna put all files to root of archive folder.zip with structure:
```
file1.txt
file2.txt
file3.txt
subfolder/file4.txt
```

I tried like this:
```
files, err := archiver.FilesFromDisk(nil, map[string]string{
	"/path/on/disk/folder/":    "",
	"/path/on/disk/folder/":    "/",
	"/path/on/disk/folder/":    ".",
	"/path/on/disk/folder":     "",
})
```

**Comment by mholt** [comment]
@nicola-spb Perfect, thanks. I'm headed out in a moment for lunch, but can you tell me real quick what the result is when you do this variant:

```go
files, err := archiver.FilesFromDisk(nil, map[string]string{
	"/path/on/disk/folder":    ""
})
```

Because I think that should do what you're looking for... :thinking:

**Comment by nicola-spb** [comment]
@mholt I tried now. It make archive with stucture:

```
folder/file1.txt
folder/file2.txt
folder/file3.txt
folder/subfolder/file4.txt
```

**Comment by nicola-spb** [comment]
And when I tried before I had strange result with this:
`"/path/on/disk/folder/":    ".",`

It created archive with folder "." and have this structure:
```
.
file1.txt
file2.txt
file3.txt
```
Maybe it's bug...

**Comment by mholt** [comment]
@nicola-spb You really like breaking my code huh :laughing: 

I opened #332 which should hopefully address your needs:

```
files, err := archiver.FilesFromDisk(nil, map[string]string{
	"/path/on/disk/folder/": "",
})
```

I have not yet looked into the "." input, that will probably have to happen another day.

**Comment by nicola-spb** [comment]
@mholt 

Hi, when I use create archive and use archiver.FilesFromDisk with ZIP format then I have broken archive. I cannot extract archive (in Ubuntu) and when I open archive in windows I see folder sourceDir (root) but archive should not have it's folder.

```
format := archiver.CompressedArchive{
	Archival: archiver.Zip{},
}

err = archive.MakeArchive(ctx, tmpDir, archivePath, format)
```

```
// MakeArchive make archive of files in directory.
func MakeArchive(ctx context.Context, sourceDir string, archivePath string, format archiver.CompressedArchive) error {
	sep := string(filepath.Separator)

	// add "/" to the path "path/folder/"
	if !strings.HasSuffix(sourceDir, sep) {
		sourceDir = sourceDir + sep
	}

	// map files on disk to their paths in the archive
	files, err := archiver.FilesFromDisk(&archiver.FromDiskOptions{FollowSymlinks:  true}, map[string]string{
		sourceDir: "",
	})
	if err != nil {
		return err
	}

	// create the output file we'll write to
	out, err := os.Create(archivePath)
	if err != nil {
		return err
	}
	defer out.Close()

	// create the archive
	err = format.Archive(ctx, out, files)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by mholt** [comment]
@nicola-spb Can you please open a new issue and provide enough information for me to reproduce the behavior as simply as possible? (Directory structure, a full `main()` function that I can run to repro, etc.) Thanks
