### ISSUE TITLE
ArchiveFS stat and using section reader

### ISSUE THREAD

**Issue by WeidiDeng** [mholt/archiver#334]
## What version of the package or command are you using?

v4.0.0-alpha.6

## What are you trying to do?

Because golang embed doesn't compress fs, I precompressed the file and embed it to a string, and use that string as section reader to use as fs.FS. Because other parts of the program use archiver, I want to use it here as well.

## What steps did you take?

[assets.tar.gz](https://github.com/mholt/archiver/files/8519319/assets.tar.gz)

```
package main

import (
	_ "embed"
	"github.com/mholt/archiver/v4"
	"io"
	"io/fs"
	"log"
	"strings"
)

var (
	//go:embed assets.tar.gz
	s string
	F fs.FS
)

func init() {
	reader := strings.NewReader(s)
	format, _, _ := archiver.Identify("", reader)
	F = archiver.ArchiveFS{
		Stream: io.NewSectionReader(reader, 0, reader.Size()),
		Format: format.(archiver.Archival),
		Prefix: "",
	}
	//F, _ = archiver.FileSystem("assets.tar.gz") // actually return an ArchiveFS
}

func main() {
	log.Println(F.Open("assets"))
	log.Println(F.Open("."))
	log.Println(fs.Stat(F, "assets"))
	log.Println(fs.Stat(F, "."))
	_ = fs.WalkDir(F, "assets", func(path string, d fs.DirEntry, err error) error {
		log.Println(path, d, err)
		return err
	})
}
```

## What did you expect to happen, and what actually happened instead?

Expected: All calls return no error.

Actual: SectionReader Variant: open(".") fail, all stat call fail. File path variant, all stat except "." return file doesn't exist error. Even though when the path is successfully opened, the returned file stat method return successfully.

## How do you think this should be fixed?

SectionReader should behave the same as specifying the path. And path variant should allow stat path other than ".".

**Comment by WeidiDeng** [comment]
Strangely, if I use fs.Sub to remove "assets" prefix, there're no problems in stat and open to access build folder.

**Comment by mholt** [comment]
Thanks for the report. Just kind of a weird edge case. Can you please check and see if #335 does it for you? I was able to get it working using your repro code and archive, which was very helpful (thank you).

**Comment by WeidiDeng** [comment]
Thanks you for your commit, it is indeed fixed.
