### ISSUE TITLE
404 when serve http

### ISSUE THREAD

**Issue by WeidiDeng** [mholt/archiver#343]
## What version of the package or command are you using?
v4.0.0-alpha.7

## What are you trying to do?
Serve archiveFS using http.FileServer

## What steps did you take?
[caddy.tar.gz](https://github.com/mholt/archiver/files/9359020/caddy.tar.gz)

```
func TestServer(t *testing.T) {
	file := "caddy.tar.gz"
	fs, _ := archiver.FileSystem(file)
	server := http.FileServer(http.FS(fs))
	http.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
		// disable range support
		writer.Header().Set("Accept-Ranges", "none")
		request.Header.Del("Range")

		// disable content-type sniffing
		ctype := mime.TypeByExtension(filepath.Ext(request.URL.Path))
		writer.Header()["Content-Type"] = nil
		if ctype != "" {
			writer.Header().Set("Content-Type", ctype)
		}
		server.ServeHTTP(writer, request)
	})
	t.Fatal(http.ListenAndServe("localhost:1234", nil))
}
```

Open http://localhost:1234

## What did you expect to happen, and what actually happened instead?
Browsing archive content on the fly. But every link when opened return 404.

## How do you think this should be fixed?
When matching files, nomalize NameInArchive to be cross platform compatible.

## Please link to any related issues, pull requests, and/or discussion
None

**Comment by mholt** [comment]
Quit breaking my code, @WeidiDeng :smile: 

That is a bit odd. I've been able to reproduce this (thanks for the report), but what's the use case of having a directory named "." in the archive?

**Comment by mholt** [comment]
Anyway, I'm a bit torn what to do with this. When you say "normalize NameInArchive to be cross-platform compatible," what do you propose exactly? It technically already is "cross-platform compatible," it's just that Go's standard HTTP file server cleans paths to remove `.` elements (via `path.Clean()`).

**Comment by WeidiDeng** [comment]
> Quit breaking my code, @WeidiDeng ! 😄
> 
> That is a bit odd. I've been able to reproduce this (thanks for the report), but what's the use case of having a directory named "." in the archive?

```
git clone https://git/caddy
cd caddy
tar -czvf ../caddy.tar.gz
```

That's how the file is created.

**Comment by mholt** [comment]
@WeidiDeng Right, so it creates a folder in the archive named literal `.` -- is that what you intended? Why?

**Comment by WeidiDeng** [comment]
> @WeidiDeng Right, so it creates a folder in the archive named literal `.` -- is that what you intended? Why?

without ., I can't even create the archive, that's how tar is working. I could go up a directory and replace . with caddy but that's required for tar to know which directory to pack.

**Comment by mholt** [comment]
So, don't you want `*` instead of `.`?

**Comment by WeidiDeng** [comment]
It's a matter of habit, even if I change mine, there are others use . and archiveFS can't handle that.

**Comment by WeidiDeng** [comment]
Even if I use *, cmd directory below root returns a go file instead of directory listing, there are definitely corner cases to be considered.

**Comment by mholt** [comment]
>  ArchiveFS should handle those appropriately.

I think we do handle it appropriately... the "bug" (if it can be called that) is in the std lib http.FileServer.

> Even if I use *, cmd directory below root returns a go file instead of directory listing,

What do you mean? `*` worked fine for me, can you be more specific? What is the actual command, dir structure, and result?

**Comment by WeidiDeng** [comment]
> > ArchiveFS should handle those appropriately.
> 
> I think we do handle it appropriately... the "bug" (if it can be called that) is in the std lib http.FileServer.
> 
> > Even if I use *, cmd directory below root returns a go file instead of directory listing,
> 
> What do you mean? `*` worked fine for me, can you be more specific? What is the actual command, dir structure, and result?

The result archive from * command doesn't have top level . directory.

Also, in open, there exists a similar problem like [330](https://github.com/mholt/archiver/issues/330), directory doesn't have entry in the archive file.

**Comment by WeidiDeng** [comment]
All in all, I think precomputing a path to FileInfo map is helpful, at least Extract interface is stable enough to do this. On the fly traversal simply has too many corner cases to consider.

**Comment by mholt** [comment]
> The result archive from * command doesn't have top level . directory.

That sounds like the desired result then. I think that is probably the best/proper fix. That's just how `tar` works: if you give it a directory, it'll tar a directory. So I don't find the behavior surprising; maybe open an issue upstream with Go if you think the behavior of http.FileServer (or http.FS) should be changed. :+1:

> Also, in open, there exists a similar problem like https://github.com/mholt/archiver/issues/330, directory doesn't have entry in the archive file.

Can you elaborate on that?

**Comment by WeidiDeng** [comment]
> > The result archive from * command doesn't have top level . directory.
> 
> That sounds like the desired result then. I think that is probably the best/proper fix. That's just how `tar` works: if you give it a directory, it'll tar a directory. So I don't find the behavior surprising; maybe open an issue upstream with Go if you think the behavior of http.FileServer (or http.FS) should be changed. 👍
> 

Rar suffers from the same problem. Several of my rar files have top level . directory, others don't. If you don't like it, that's fine with me.

Can you at least document that even with the **normal** archive file, how to disable content-type sniffing and disable range request, that's actually helpful to know.

[this file](https://www.rarlab.com/rar/rarmacos-arm-612.tar.gz) when used directly, you can't download rar inside it directly, because golang sniff content-type and it will cause seek to fail error.

When only disable content-sniffing, browser download it fine, but aria2c can't, because it uses range request.

> > Also, in open, there exists a similar problem like #330, directory doesn't have entry in the archive file.
> 
> Can you elaborate on that?

There is not internal directory in the tar directory listing. Like in the [issue](https://github.com/mholt/archiver/issues/330). Some folders just don't have entry in archivefs.
