### ISSUE TITLE
Infinite block on reading a broken .rar

### ISSUE THREAD

**Issue by wloot** [mholt/archiver#345]
## What version of the package or command are you using?
v4.0.0-alpha.7

## What are you trying to do?
I first open the archives using `Identify()`, the `Extract()` to open/read every files inside of it.

## What steps did you take?
```
	file, err := os.Open(filename)
	format, input, err := archiver.Identify("", file)
        ex, ok := format.(archiver.Extractor)
        ex.Extract(context.Background(), input, nil, func(_ context.Context, f archiver.File) error {
		if f.IsDir() {
			return nil
		}
		rc, err := f.Open()
		if err != nil {
			return nil
		}
		data, _ := io.ReadAll(rc)
		rc.Close()
		return nil
	})
```
The above code(some error handling is omitted) works fine in general, but I have a broken .rar file that causes it infinite reading.
File link: https://we.tl/t-ypgSNYl5Sc

## What did you expect to happen, and what actually happened instead?
Return a error while calling Open() or Read().

## How do you think this should be fixed?
None

## Please link to any related issues, pull requests, and/or discussion
None

## Bonus: What do you use archiver for, and do you find it useful?
None

**Comment by mholt** [comment]
Can you please upload the file to github, I'm having trouble downloading from that site and it's sketching me out.

**Comment by wloot** [comment]
> Can you please upload the file to github, I'm having trouble downloading from that site and it's sketching me out.

[[zmk.pw]Batman.Forever.1995.BluRay.720p.DTS.2Audio.x264-CHD.rar.zip](https://github.com/mholt/archiver/files/9409652/zmk.pw.Batman.Forever.1995.BluRay.720p.DTS.2Audio.x264-CHD.rar.zip)
Sorry for that, I tried and Github tells me .rar format is unsupported. I faked the suffix this time, please change it back after downloaded.

**Comment by mholt** [comment]
Thanks. I see the CPU spinning at 100% during ReadAll.

You'd want to open an issue upstream with the package implementing the rar reading: https://github.com/nwaples/rardecode

(/cc @nwaples)
