### ISSUE TITLE
encrypted

### ISSUE THREAD

**Issue by pigraining** [mholt/archiver#346]
How to confirm whether the compressed package is encrypted

**Comment by mholt** [comment]
Not currently implemented. Not really sure how to go about that, and I don't personally have a need for it, but anyone is welcome to submit a proposal here for how it would work!

**Comment by mholt** [comment]
Going to close this since there's nothing really actionable I can do with this, but if anyone else finds this and wants to submit a proposal then we can work with that. Thanks!
