### ISSUE TITLE
How about providing a dummy archiver?

### ISSUE THREAD

**Issue by orca-zhang** [mholt/archiver#347]
Dear Matt,

Thanks to your great lib.
What I'm working is optional compressed extensions, so non-compressed ones that they do nothing about compression/decompression are included.

## What would you like to have changed?

provide a dummy implementation

## Why is this feature a useful, necessary, and/or important addition to this project?

easy to deal with non-compressed options

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

DIY or writing some special hard codes

## Please link to any relevant issues, pull requests, or other discussions.

maybe it will look like bellows (in v3)
``` go
type DummyArchiver struct{}

func (DummyArchiver) CheckExt(string) error { return nil }
func (DummyArchiver) Compress(in io.Reader, out io.Writer) error {
	_, err := io.Copy(out, in)
	return err
}
func (DummyArchiver) Decompress(in io.Reader, out io.Writer) error {
	_, err := io.Copy(out, in)
	return err
}
```

**Comment by mholt** [comment]
To clarify, are you asking about v3 or v4? Because I'm no longer developing for v3...
