### ISSUE TITLE
support zstd seekable compression

### ISSUE THREAD

**Issue by electricface** [mholt/archiver#348]
## What would you like to have changed?

https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md
https://libraries.io/go/github.com%2FSaveTheRbtz%2Fzstd-seekable-format-go
https://github.com/fuuzetsu/zstd-seekable-s3
https://github.com/martinellimarco/t2sz

**Comment by mholt** [comment]
I would love to have the Seeker interface implemented for all compression/archive formats!

I don't understand the compression or archive formats well enough to do this myself. We use @klauspost's excellent compression libraries (esp. for zstd), so maybe he has some insights on the feasibility of this.

**Comment by klauspost** [comment]
s2/snappy has implemented [Stream Seek Index](https://github.com/klauspost/compress/tree/master/s2#stream-seek-index) that are placed at the end of the stream.

I currently have no support for zstd seeking, since it is pretty much unused. I don't have any current plans of implementing it.

**Comment by mholt** [comment]
Thanks Klaus!

What's your use case @electricface ?

**Comment by klauspost** [comment]
I haven't seen [zstd-seekable-format-go](https://github.com/SaveTheRbtz/zstd-seekable-format-go) before. Looks to be an abstraction over my package, so it looks like I might not even need to implement it :)

**Comment by electricface** [comment]
I should have no application scenarios.

**Comment by mholt** [comment]
I see. Well, we can consider it if there's a compelling use case. (Feel free to reopen if this has a real use case.)
