### ISSUE TITLE
Add common quality/compression interface

### ISSUE THREAD

**Issue by zeripath** [mholt/archiver#351]
## What would you like to have changed?
Add a common interface to allow setting of compression level using int. e.g.

```
type ConfigurableCompressionLevel interface {
  SetCompressionLevel(int) 
}
```

(this could be `SetCompressionLevel(int) bool` to say whether this level is acceptable.)

## Why is this feature a useful, necessary, and/or important addition to this project?
Many archivers/compressors have a way of setting compression level and this would allow these to be exposed in a common fashion.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
1. We can continue by casting as individual types of archiver
2. Could use reflect.ValueOf(...).FieldByName("CompressionLevel").SetInt(...) / "Quality" as appropriate

## Please link to any relevant issues, pull requests, or other discussions.
N/A at the moment.

**Comment by zeripath** [comment]
I see the API has changed considerably for v4 and this may not be as useful.

**Comment by mholt** [comment]
Thanks; I think if this was implemented it should be an optional interface that can be type-asserted to use, but I don't know how useful this would be since if you're customizing a compressor you usually are working with the concrete type already anyways.

**Comment by mholt** [comment]
I don't know of a good way to make this work cross-format, though, I think it might be best for the user/caller to just set the options per-format instead.
