### ISSUE TITLE
Expose CompressionLevel for Zstd

### ISSUE THREAD

**Issue by zeripath** [mholt/archiver#352]
## What would you like to have changed?
The TarZstd and Zstd don't express a way of setting the compression level.

## Why is this feature a useful, necessary, and/or important addition to this project?
Most compressors already expose this.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
We would have to abandon the TarZstd and Zstd wrappers and handle them directly ourselves.

## Please link to any relevant issues, pull requests, or other discussions.
#351

**Comment by mholt** [comment]
Thanks for the feature request! :) (Sorry it took me so long to even see it. Been busy catching up.)

**Comment by mholt** [comment]
@zeripath Wait, don't you just have to set `EncoderLevel` in the `EncoderOptions`? https://pkg.go.dev/github.com/mholt/archiver/v4#Zstd - see https://pkg.go.dev/github.com/klauspost/compress/zstd#WithEncoderLevel
