### ISSUE TITLE
v4 will decompress docx

### ISSUE THREAD

**Issue by drwpeng** [mholt/archiver#359]
v4 will decompress docx/xlsx/pptx, are there any plans to fix this

**Comment by mholt** [comment]
From what I understand, those files are zip files with contents that can be extracted. What is broken, exactly? As I don't have Windows or Office products, can you provide a minimally reproducible example?

**Comment by drwpeng** [comment]
Yes, docx is also a zip type. 
My task is to judge all files type. If it is a compressed file, decompress it. Then docx will be decompressed as a zip file. 
Generally, docx should not be decompressed.

**Comment by mholt** [comment]
That's up to you, I think. If someone wants to access files within a docx archive, then they should extract it. If someone doesn't want to, they should skip it.

I think that's something that's up to the application developer more than this library...

(Closing, but feel free to continue discussion, especially if you feel like you have a compelling use case for this lib interpreting intentions like this, let me know!)
