### ISSUE TITLE
Using rewindReader as a public type allows external access

### ISSUE THREAD

**Issue by drwpeng** [mholt/archiver#361]
## What would you like to have changed?

Make `rewindreader`-related content public methods

## Why is this feature a useful, necessary, and/or important addition to this project?

When I recursively extract the file, I might read the reader content.
If I wanted to keep using reader, the `rewindreader` was vital.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

To rewind the reader, I had to implement the rewindReader myself, which felt like a hassle.
If you could make `rewindReader` a public method, that would really help me.

**Comment by mholt** [comment]
Hmm, I'm worried that it'd cause scope creep... that's currently an internal utility for identifying an archive format. Is it really that useful to export?

**Comment by mholt** [comment]
Could you use the `bufio` package instead? https://pkg.go.dev/bufio#Reader

This does feel like something more general than archives, so I'm not sure exporting it is a good fit for our package.

Closing, but open to continuing the discussion; I could probably be convinced if there's no other way.
