### ISSUE TITLE
go:embed via []byte stream or fs.File support

### ISSUE THREAD

**Issue by alx52** [mholt/archiver#363]
## What would you like to have changed?
Need the feature to unarchiving and extract of archives embedded in the executable file:
```
//go:embed archive.tar.xz
var embeddedFile []byte
```

There are two possible ways of implementation:

- By passing io.Reader stream like `bytes.NewReader(embeddedFile)` (universal option not only for embedded)
- By passing fs.File like `embed.FS.Open("archive.tar.xz")`

## Why is this feature a useful, necessary, and/or important addition to this project?
This is necessary for the delivery of a single executable file

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
```
txz.archiver.NewTarXz()
txz.Open(bytes.NewReader(embeddedFile), 0)
for ... // walk through each file until EOF
file, _ := txz.Read()
// and then the contents of the Unarchive() are repeated
```
But the easiest way is branching for adding a function like:
`func (t *Tar) UnarchiveBytes(source *[]byte, destination string) error`

**Comment by alx52** [comment]
I tried to solve it using version 4, but I couldn't find a way to unarchive

**Comment by korpa** [comment]
@mholt It would be really cool to have this feature. Any suggestions if it is possible already or if you will implement it?

**Comment by mholt** [comment]
Thanks for the feature request. I haven't tried this, but does the example from the README (slightly modified for embedded .tar.xz) not work? (v4)

```go
format := archiver.CompressedArchive{
	Compression: archiver.Xz{},
	Archival:    archiver.Tar{},
}


handler := func(ctx context.Context, f archiver.File) error {
	// do something with the file
	return nil
}

err := format.Extract(ctx, bytes.NewReader(embeddedFile), nil, handler)
if err != nil {
	return err
}
```

Since I believe this can already work just fine, I will close this, but feel free to continue discussion and if something is not working we can reopen it.
