### ISSUE TITLE
How to provide dictionary for ZSTD encoder/decoder?

### ISSUE THREAD

**Issue by krystian-panek-wttech** [mholt/archiver#366]
ZSTD format works effectively when `dict` is provided:
https://github.com/klauspost/compress/blob/master/zstd/encoder_options.go#L31

see graphs: https://github.com/facebook/zstd#the-case-for-small-data-compression

I wonder how to provide `dict` value for Encoder/Decoder options defined here:
https://github.com/mholt/archiver/blob/master/zstd.go#L17-L18
Do I need to register own format? There is no option to update options for already registered formats?

I am currently using following snippet and wondering what I need to do to leverage fully ZSTD format by using dictionaries.

```go
archiver.Archive([]string{sourceDir}, "myfile/tar.zst)
```

Any ideas?
Greetings, Krystian

**Comment by mholt** [comment]
Hi Krystian, thanks for the question!

I don't know much about this myself. But I learned something about it from the README of the compress package we use: https://pkg.go.dev/github.com/klauspost/compress/zstd#section-readme (see the "Dictionaries" heading)

As for configuring the Zstd format, you can get EOption and DOption values from the compress package: https://pkg.go.dev/github.com/klauspost/compress/zstd#pkg-index (see types EOption and DOption -- some are dictionary-related)

Hope that helps!

**Comment by krystian-panek-wttech** [comment]
not really but ok ;) your lib is rather providing a facade that does not offer to customize format-specific options.

today I even struggled with another problem. I am instantiating TarZstd archiver intentionally but I want to output the file with the custom extension, let's say `myfile.aemb`- I am trying to hide the archive format to make it not explicit. I cannot do that because your lib is checking extension twice. at first when trying to auto-detect the correct archiver,  then the second time when calling the detected archiver. this makes it impossible to use different archive extensions than those supported.

it's just FYI. I could live with it ;) since you are working on 4.x I thought that you may want to address that case as well.

**Comment by mholt** [comment]
@krystian-panek-wttech 

> @mholt not really but ok ;) your lib is rather providing a facade that does not offer to customize format-specific options.

Sorry, but huh? You linked to the exported struct you can set the options on:

https://github.com/mholt/archiver/blob/f1ef6ebbdf2a7b10af9c44b4540fe9b953b7fba1/zstd.go#L15-L19

That lets you customize Zstd with any of the Zstandard options in the klauspost/compress package. What more do you need? 

> simply saying I am not sure if this extension checking is needed here: https://github.com/mholt/archiver/blob/v3.5.1/tarzst.go#L31

That's for Archiver v3... FYI I'm no longer maintaining that as v4 is the future.

**Comment by krystian-panek-wttech** [comment]
> we inspect file type by reading the header rather than a file extension only.

that's the clarification I wanted to read ;) cool

>  You linked to the exported struct you can set the options on:

yes sure, I could always use libs directly but I wanted just to tune settings for zstd but still supporting other formats as well

nvm, I am good with your feedback, thanks ;)
