### ISSUE TITLE
cannot archiver rar format

### ISSUE THREAD

**Issue by BTYHunter** [mholt/archiver#373]
Sorry Im not sure if archiver supports archive rar format. Below is my code.
following README file
```go
files, err := archiver.FilesFromDisk(nil, map[string]string{
    "target.txt": "file1.txt"})
if err != nil {
  fmt.Println("error")
}

// create the output file we'll write to
out, err := os.Create("example.rar")
if err != nil {
 return err
}
defer out.Close()

// we can use the CompressedArchive type to gzip a tarball
// (compression is not required; you could use Tar directly)
format := archiver.CompressedArchive{
//  Compression: archiver.Gz{},
  Archival:    archiver.Rar{},
}

// create the archive
err = format.Archive(context.Background(), out, files)
if err != nil {
 return err
}
fmt.Printf("OK")
```
the `example.rar` file will be created, but when I extract this file by winrar (on Windows), its show that  `example.rar`  'the Archive Is Either in Unknown Format or Damaged'.

**Comment by mholt** [comment]
Sorry, but please even check the documentation first.

As our README says:

> - .rar (read-only)

And the godoc:

> Archive is not implemented for RAR

This is because RAR is a proprietary format and a license is required to create RAR archives.

**Comment by BTYHunter** [comment]
thanks
