### ISSUE TITLE
Unable to decrypt 7-ZIP file with password (err: breader.ReadByte: no data!)

### ISSUE THREAD

**Issue by zollty** [mholt/archiver#375]
## What version of the package or command are you using?
v4.0.0-alpha.7

## What are you trying to do?
Decompress 7-ZIP file with password

## What steps did you take?
```go
func TestOpenReaderWithPassword(t *testing.T) {
	t.Parallel()

	tables := []struct {
		name, file, password string
	}{
		{
			name:     "xxxx header compression",
			file:     "7zcracker.7z",
			password: "876",
		},
	}
....
```
see:  [reader_test.go](https://github.com/bodgit/sevenzip/blob/master/reader_test.go#L149)
the file url: [download](https://app.uat.paramst.cn/static/7zcracker.7z)
the file is created by "7z2201-x64.exe" （from [www.7-zip.org](https://www.7-zip.org)） with default options.

## What did you expect to happen, and what actually happened instead?
Err:  breader.ReadByte: no data !
```txt
Running tool: D:\__SYNC1\Softwares\Go\bin\go.exe test -timeout 30s -run ^TestOpenReaderWithPassword$ github.com/bodgit/sevenzip

--- FAIL: TestOpenReaderWithPassword (0.00s)
    --- FAIL: TestOpenReaderWithPassword/xxxx_header_compression (1.59s)
        d:\__SYNC2\go-path\src\zollty.com\test\sevenzip\reader_test.go:183: breader.ReadByte: no data
FAIL
FAIL	github.com/bodgit/sevenzip	3.581s
FAIL
```

After my testing:   

All 7-zip encrypted files created by  software [7-zip](https://www.7-zip.org) (official windows x64 version, default options)  cannot be decrypted.    

but files encrypted by another software [Bandzip ](https://en.bandisoft.com/) can be decrypted normally.

**Comment by mholt** [comment]
We don't actually do anything with decryption, issue must be filed upstream.
