### ISSUE TITLE
RAR signature not found

### ISSUE THREAD

**Issue by Krevedos** [mholt/archiver#378]
Hi. I am getting an error when trying to unzip a file. (RAR format)

Error like this : ("opening rar archive for reading: rardecode: RAR signature not found")

## What version of the package or command are you using?   
      v3.1.1

## What are you trying to do?
      I am trying to unzip a file

## What steps did you take?
      I use  rar.Unarchive(src, dest)

I archived the file in zip, because there is no way to attach a file in rar

[Price-39-x.rar.zip](https://github.com/mholt/archiver/files/11332941/Price-39-x.rar.zip)

**Comment by mholt** [comment]
Does the error happen in v4? v3 isn't really maintained anymore.

**Comment by Krevedos** [comment]
@mholt yes, in v4 i have error too.

**Comment by Krevedos** [comment]
@mholt yes, in v4 i got an error like "rardecode: RAR signature not found"

**Comment by mholt** [comment]
@Krevedos Thanks for checking. I downloaded the file you sent me and extracted it so the .rar was on my file system. After a quick look, that's not a RAR file. The first bytes are `PK\x03\x04` which is a ZIP file.

**Comment by Krevedos** [comment]
@mholt  This file is sent to me by the supplier, so I don't know how it was created.  I will try to contact the supplier and learn more details about this file... THX
