### ISSUE TITLE
If overwrite is enabled for unarchive, and the file being overwritten is a symlink, then it tries to follow the symlink, rather than replace it

### ISSUE THREAD

**Issue by deitch** [mholt/archiver#380]
## What version of the package or command are you using?

v3.5.1

## What are you trying to do?

Enable overwrite when unarchiving, then replace symlinks

## What steps did you take?

There are two test cases, but they are the same root case.

First test case.

1. Create a directory, e.g. `/tmp/tar`
2. Create a file and a link pointing to the file.
3. tar them up
4. replace the link with a real file with different content
5. Add that new file to the archive
6. See that the archive has duplicates, which is normal for tars
7. Run `Unarchive`
8. See that rather than 2 files, there is one file and a link, and the file's contents have been changed

```bash
$ mkdir /tmp/tar
$ cd /tmp/tar
$ echo file > file
$ ln -s file link
$ tar -cvf /tmp/conflict.tar .
$ rm link
$ echo other > link
$ tar -rvf /tmp/conflict.tar ./link
$ tar -tvf /tmp/conflict.tar
drwxr-xr-x  0 root wheel       0 May 11 10:56 ./
-rw-r--r--  0 root wheel       5 May 11 10:56 ./file
lrwxr-xr-x  0 root wheel       0 May 11 10:56 ./link -> file
-rw-r--r--  0 root wheel       5 May 11 10:57 ./link
```

Now run the unarchiver, and see that we have two issues: there is a link rather than the second file, and the contents of `file` are **not** `"file"` but rather `"other"`.

```bash
$ go run . /tmp/conflict.tar /tmp/open
$ ls -l /tmp/open
-rw-r--r--  1 root  wheel  6 May 11 11:12 file
lrwxr-xr-x  1 root  wheel  4 May 11 11:12 link -> file
$ cat /tmp/open/file
other
```

Here is the sample program I used to recreate it:

```go
package main


import (
	"log"
	"os"

	"github.com/mholt/archiver/v3"
)

func main() {
	if len(os.Args) < 3 {
		log.Fatalf("usage: %s tarFile destination_dir", os.Args[0])
	}
	tarFile, dest := os.Args[1], os.Args[2]

	unarchiver := archiver.Tar{}
	unarchiver.OverwriteExisting = true

	if err := unarchiver.Unarchive(tarFile, dest); err != nil {
		log.Fatalf("error: %v", err)
	}
	log.Printf("success")
}
```

Second test case (which is what originally led me to this problem).

1. Create a directory, e.g. `/tmp/tar`
2. Create a file and a link pointing to _somewhere protected_.
3. tar them up
4. replace the link with a real file with different content
5. Add that new file to the archive
6. See that the archive has duplicates, which is normal for tars
7. Run `Unarchive`
8. See that the unarchive fails

```bash
$ mkdir /tmp/tar
$ cd /tmp/tar
$ echo file > file
$ ln -s /bin/sh link
$ tar -cvf /tmp/conflict.tar .
$ rm link
$ echo other > link
$ tar -rvf /tmp/conflict.tar ./link
$ tar -tvf /tmp/conflict.tar
drwxr-xr-x  0 root wheel       0 May 11 11:24 ./
-rw-r--r--  0 root wheel       5 May 11 10:56 ./file
lrwxr-xr-x  0 root wheel       0 May 11 11:24 ./link -> /bin/sh
-rw-r--r--  0 root wheel       6 May 11 11:24 ./link```

Now run the unarchiver, and see that it fails, because it tries to overwrite `/bin/sh` (pointed to by the link) rather than the link itself. 

```bash
$ go run . /tmp/conflict.tar /tmp/open
2023/05/11 11:25:03 error: reading file in tar archive: /tmp/open/link: creating new file: open /tmp/open/link: operation not permitted
exit status 1
```

## What did you expect to happen, and what actually happened instead?

The link is replaced, rather than followed

## How do you think this should be fixed?

In `writeNewFile()` Check if file is a link and remove it _before_ doing `os.Create()`, which follows links.

Line is [here](https://github.com/mholt/archiver/blob/v3.5.1/archiver.go#L298)

## Bonus: What do you use archiver for, and do you find it useful?

I came to it through working on syft, which is used in a project with which I am involved.

**Comment by mholt** [comment]
Hi, thanks for the issue. I'm no longer supporting v3 though -- does this happen in v4?

**Comment by deitch** [comment]
That is a good question. Now that I have a sample, I can try it out. Reporting back soon.

**Comment by deitch** [comment]
Yeah, it does. I will update the issue. But the fix likely is not the same

**Comment by deitch** [comment]
Actually, one sec. I might have run the wrong thing. I will post back here shortly.

**Comment by deitch** [comment]
Actually, how do I test? [v4.Tar](https://pkg.go.dev/github.com/mholt/archiver/v4#Tar) doesn't have `OverwriteExisting`.

**Comment by mholt** [comment]
D'oh, I'm sorry -- v4 doesn't have `OverwriteExisting` because we changed how v4 does extractions. Archiver v4 doesn't actually do disk operations, it only does stream operations. So you call [`Extract()`](https://pkg.go.dev/github.com/mholt/archiver/v4#Extractor.Extract) and then you open the files to write to disk, this resolves the issue since you have complete control over it. :100:

**Comment by deitch** [comment]
I am trying to wrap my head around that. So it is similar to [fs.WalkDir()](https://pkg.go.dev/io/fs#WalkDir), where you provide it a handler, and then do what you want with it?

Come to think of it, does it actually implement `fs.FS` so that you could use `fs.WalkDir()` on it?

**Comment by mholt** [comment]
Yes, you can call [`archiver.FileSystem()`](https://pkg.go.dev/github.com/mholt/archiver/v4#FileSystem) to get a `fs.FS` which you can walk. The extract method is a little similar to walking, and indeed it does let you walk the archive -- it may be more efficient to use Extract though, unless you need `fs.FS` for something.

**Comment by mholt** [comment]
No problem. Just curious, what are you using archiver for?

Thanks for your detailed issue report btw, would love to see more like that.

**Comment by deitch** [comment]
It is in [syft](https://github.com/anchore/syft). 

FYI, I also have some tar management in [go-apk](https://github.com/chainguard-dev/go-apk), under [here](https://github.com/chainguard-dev/go-apk/tree/main/pkg/tarball). I wouldn't mind repeating it.

**Comment by mholt** [comment]
Cool! We use syft with [Caddy](https://github.com/caddyserver/caddy) as part of our release workflow.
