### ISSUE TITLE
Return io.Reader from archiver.FileSystem.Open(filename)

### ISSUE THREAD

**Issue by chieftinkerer** [mholt/archiver#381]
Thank you for creating Archiver.  It looks like it will be a great library for my use case.

## What would you like to have changed?
It looks like archiver.FileSystem.Open(filename) returns an Archiver fs.File.  I need an io.Reader so that I can use bufio.Scanner to perform buffered reads and splits of the file(s) in the archive.  Can you tell me how to get an io.Reader using your virtual filesystem WalkDir, or can another function be added to return it?

Thanks.

## Why is this feature a useful, necessary, and/or important addition to this project?
This would allow buffered reads which is necessary for very large files in the archives, and would allow using the bufio.Scanner.Split function to process file chunks split be tokens.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I looked for a way to get an io.Reader from your fs.File object, but it looks like it does not support that.

## Please link to any relevant issues, pull requests, or other discussions.
Nothing else at this time.

Thank you.

**Comment by mholt** [comment]
`fs.File` is also `io.Reader`: https://pkg.go.dev/io/fs#File

Hope that helps!
