### ISSUE TITLE
file 2G.file: writing data: archive/tar: write too long

### ISSUE THREAD

**Issue by halfcrazy** [mholt/archiver#387]
## What version of the package or command are you using?

github.com/mholt/archiver/v4 v4.0.0-alpha.8

## What are you trying to do?

create an archive with continuous writing contents to the source file.

## What steps did you take?

prepare data with `dd if=/dev/urandom of=/2G.file bs=1M count=2048`

open a new window, and run scripts
```
while true; do
    echo "data..." >> 2G.file
    sleep 0.1
done
```

```
package main

import (
	"context"
	"github.com/mholt/archiver/v4"
	"os"
)

func main() {

	files, err := archiver.FilesFromDisk(nil, map[string]string{
		"/2G.file": "",
	})
	if err != nil {
		panic(err)
	}

	// create the output file we'll write to
	tmpFileName := "/tmp/aa"
	out, err := os.Create(tmpFileName)
	if err != nil {
		panic(err)
	}
	defer out.Close()

	// we can use the CompressedArchive type to gzip a tarball
	// (compression is not required; you could use Tar directly)
	format := archiver.CompressedArchive{
		Compression: archiver.Gz{},
		Archival:    archiver.Tar{},
	}

	// create the archive
	err = format.Archive(context.Background(), out, files)
	if err != nil {
		panic(err)
	}
}
```

## What did you expect to happen, and what actually happened instead?

Expect: no errors report
Actually: panic: file 2G.file: writing data: archive/tar: write too long

## Please link to any related issues, pull requests, and/or discussion

https://github.com/mholt/archiver/pull/8

## Bonus: What do you use archiver for, and do you find it useful?

My use case is to create a backup file for my living database.

**Comment by mholt** [comment]
Thanks for the PR! I left a comment since I need help understanding it better.
