### ISSUE TITLE
Listing files of an Encrypted RAR Without Password Input

### ISSUE THREAD

**Issue by ganeshrvel** [mholt/archiver#389]
Is there a way to list the files contained inside an encrypted RAR archive without providing the password? Looking for methods or workarounds to view the file names without decrypting the entire archive.

**Comment by mholt** [comment]
Hmm, not sure about that one -- closing in favor of https://github.com/nwaples/rardecode/issues/34 which will probably get you a better answer, since we just use the lib -- that one actually implements the password support.
