### ISSUE TITLE
Is there support for password protected archives?

### ISSUE THREAD

**Issue by RayBB** [mholt/archiver#39]

**Comment by mholt** [comment]
There isn't, no. Pull requests welcome ;)

**Comment by RayBB** [comment]
I'd be willing to give it a shot but I wouldn't even know where to begin.

**Comment by mholt** [comment]
Haha, I wouldn't either -- I don't know much about the format. The Go standard lib [doesn't support it so we'd have to use an archive/zip replacement](https://github.com/golang/go/issues/12081) or do it ourselves somehow. Sorry, I'm not much help here. :smile:

**Comment by mholt** [comment]
The rar decoder supports this; will ship in #99.

**Comment by enumag** [comment]
Is there a support for password protected zip archives or only rar?

**Comment by mholt** [comment]
I'm not sure of a stable and maintained library that can read password-protected zip archives. (Happy to be shown one, though.)
