### ISSUE TITLE
The CompressFile function does not work

### ISSUE THREAD

**Issue by beifeng778** [mholt/archiver#390]
Failure to compress files with CompressFile

## What version of the package or command are you using?

github.com/mholt/archiver/v3

## What steps did you take?

```
err := archiver.CompressFile("test66.tar", "test66.tar.gz")
	if err != nil {
		panic(err)
	}
output:
    panic: format specified by destination filename is not a recognized compression algorithm: test66.tar.gz

```

**Comment by mholt** [comment]
Did you mean to close this?

Please upload a file that reproduces the bug.

**Comment by beifeng778** [comment]
Yes, I found the answer in other issue.
