### ISSUE TITLE
Compare and sync two directories

### ISSUE THREAD

**Issue by keith6014** [mholt/archiver#395]
I have been using rclone/rsync to sync two directories. However, I am in a situation where my local disk is much smaller than my ec2 instance. So, I compress the data on my local disk.  Is there a way for this library to sync two directories, similar to rsync/rclone, and but checking if the target file is compressed? It doesn't need to validate the destination file, just need to check its modtime, and compressed with extension (.bz).

**Comment by mholt** [comment]
This library in and of itself doesn't do any sync work. It only reads and creates archives/compressed files.

If you're already writing Go code, you can use this lib to open an archive file as if it were a file system and then treat it like a folder on disk using the `io/fs` package, from which you can then do the copying to a remote server.

Hope that helps!
