### ISSUE TITLE
WIll there be support for just generic Archive and Extract to a dir?

### ISSUE THREAD

**Issue by aryehlev** [mholt/archiver#398]
## What would you like to have changed?
in v3 there are generic functions for archiving to a file and extracting to a folder.

## Why is this feature a useful, necessary, and/or important addition to this project?
it just can make life easier,

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
using v3.

**Comment by mholt** [comment]
Not planned at this time; duplicate of #311.
