### ISSUE TITLE
v4: Getting panic when I format.Extract and `io.Reader` is given by `os.Open(filePath)`

### ISSUE THREAD

**Issue by doronbehar** [mholt/archiver#408]
Hello,

I'm not an experienced Golang developer, but I'm trying to adapt to v4, and I'm having trouble figure out what is the issue with this code:

```go
package main
import (
	"os"
	"fmt"
	"context"
	"github.com/mholt/archiver/v4"
)
func archiveHandler(ctx context.Context, f archiver.File) error {
	fmt.Printf("%v\n", f)
	return nil
}
func main() {
	format := archiver.SevenZip{}
	reader, _ := os.Open("example.7z")
	_ = format.Extract(nil, reader, nil, archiveHandler)
	reader.Close()
}
```

(Since I was lazy to check errors, the `exmaple.7z` file must exist of course). The error is:

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5fac3c]

goroutine 1 [running]:
github.com/mholt/archiver/v4.SevenZip.Extract({0x0?, {0x0?, 0x0?}}, {0x0, 0x0}, {0x6d5500?, 0xc000200000
}, {0x0, 0x0, 0x0}, ...)
        /home/doron/.go/pkg/mod/github.com/mholt/archiver/v4@v4.0.0-alpha.8/7z.go:85 +0x23c
main.main()
        /home/doron/repos/archiver-test/main.go:21 +0x59
```

This must be super easy to fix if you know what is the problem :pray:.

**Comment by franchb** [comment]
Hello,

you are making a call to `format.Extract`  function, but you are passing `nil` as arguments.
The `ctx context.Context` argument in `format.Extract` function accepts a `Context` argument, when calling this function it would be better to use `context.Background()` or another context if you have one.

**Comment by doronbehar** [comment]
Thanks for the help! I used `context.TODO()` since I don't need it to run in the background.
