### ISSUE TITLE
RAR extract file information

### ISSUE THREAD

**Issue by DylanZhu2021** [mholt/archiver#420]
Use the code as follow to get file information such as file mod tiinme in .rar:

    f, err := os.Open(realpath)

	if err != nil {
		return nil, err
	}

	rar := archiver.Rar{}

	handleFun := func(ctx context.Context, f archiver.File) error {
		fmt.Println(f.ModTime())
	}

	err = rar.Extract(context.Background(), f, nil, handleFun)

the file time is null. However,the file such as zip,tar get right mod time.

Someone can tell me why. Thanks.

**Comment by DylanZhu2021** [comment]
> Can you provide an archive that exhibits this behavior? I don't have a rar file handy that does this.

There is a test file for rar in test.zip, you can dearchive this and get the rar file. Thanks. 
[test.zip](https://github.com/user-attachments/files/16833294/test.zip)

**Comment by mholt** [comment]
Well, I checked whether the underlying rardecode package has the dates and maybe we just weren't passing them through, but it seems that even the decoder has empty timestamps, so I opened an issue upstream: https://github.com/nwaples/rardecode/issues/39

**Comment by mholt** [comment]
This has been fixed upstream by @nwaples -- I will upgrade the dependency here soon!
