### ISSUE TITLE
Files inside zip archives being reported as directories when using fs.WalkDir()

### ISSUE THREAD

**Issue by blamoo** [mholt/archiver#430]
## What version of the package or command are you using?
(copied from go.sum)
github.com/mholt/archiver/v4 v4.0.0-alpha.9 h1:EZgAsW6DsuawxDgTtIdjCUBa2TQ6AOe9pnCidofSRtE=
github.com/mholt/archiver/v4 v4.0.0-alpha.9/go.mod h1:5D3uct315OMkMRXKwEuMB+wQi/2m5NQngKDmApqwVlo=

## What are you trying to do?
List files inside a zip file using archiver.FileSystem() and determine if they are directories or not

## What steps did you take?
```go
package main

import (
	"archive/zip"
	"context"
	"fmt"
	"io"
	"io/fs"
	"os"

	"github.com/mholt/archiver/v4"
)

func main() {
	// Create a test zip file
	zipArchive, _ := os.Create("demo.zip")
	zipWriter := zip.NewWriter(zipArchive)
	
	// Add a few files to it
	var f io.Writer
	f, _ = zipWriter.Create("001.txt")
	f.Write([]byte("test"))
	
	f, _ = zipWriter.Create("002.txt")
	f.Write([]byte("test"))
	
	f, _ = zipWriter.Create("003.txt")
	f.Write([]byte("test"))
	
	zipWriter.Close()
	zipArchive.Close()
	
	// List each entry and check if it is a dir or not
	fsys, _ := archiver.FileSystem(context.TODO(), "demo.zip", nil)
	fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		fmt.Println(path, d.IsDir())
		return nil
	})
}
```

## What did you expect to happen, and what actually happened instead?

What I expected (this is the output from v4.0.0-alpha.8):
```
. true
001.txt false
002.txt false
003.txt false
```

What I got from the same code running on v4.0.0-alpha.9:
```
. true
001.txt true
002.txt true
003.txt true
```

## Bonus: What do you use archiver for, and do you find it useful?
I'm using it for a self-hosted online manga reader that dynamically loads .cbz and .cbr files (.zip and .rar with a different extension) and unzipped folders.
This package fits my needs like a glove. Before I found out about this package, I had to write 3 different functions to parse zip, rar and folders into a common interface.

**Comment by mholt** [comment]
Huh, thanks -- I think I found the problem, will push a fix as soon as I can.

**Comment by mholt** [comment]
@blamoo I think I fixed it, if you want to verify -- your sample program works as expected for me now, as well as with some sample archives I tested.
