### ISSUE TITLE
Error unpacking large archive writing file: rardecode: ...

### ISSUE THREAD

**Issue by Galamoon** [mholt/archiver#47]
I have problems with unpacking a large rar archive, the archive itself takes about 6GB and unpacked 25GB. The archive contains XML files with a database of Russian addresses.
You can download it from the official site http://fias.nalog.ru or from the direct link http://fias.nalog.ru/Public/Downloads/Actual/fias_xml.rar
The full error text
`ERROR: 2017/10/12 00:37:10 unpack.go:12: Error unpack archive: data\AS_HOUSE_20171008_bed24a8e-4646-448d-acb8-8de765818389.XML: writing file: rardecode: decoder expected more data than is in packed file`
The function I'm using is
```go
package unpack
import (
	"github.com/mholt/archiver"
	"os"
	"../loger"
)
func Unpack(dest string, archive string) {
	err := archiver.Rar.Open(archive, dest)
	if err != nil {
		loger.Error.Printf("Error unpack archive: %v\n", err)
		os.Exit(1)
	}
}
```
I'm new to Go, you can tell me what the problem is.

**Comment by mholt** [comment]
Huh, I have no clue. It might be worth taking this up with the author of the rar package directly: https://github.com/nwaples/rardecode

I will close this since I'm not sure that this is a bug in archiver, per-se -- I might be wrong though, and we can open this back up if that's the case.

**Comment by Galamoon** [comment]
Something tells me that waiting for an answer there will take a long time. You know some alternatives to archivers for Go not based on nwaples / rardecode

**Comment by mholt** [comment]
I do not know of other rar decoding packages in (pure) Go, sorry.
