### ISSUE TITLE
ISO/Squashfile

### ISSUE THREAD

**Issue by necrose99** [mholt/archiver#49]
as a docker drop in   

ISO_URL=

filter to trash iso ,  get squashfs and unpack @ /  would be a nice to have so far i have a slower python script nearly done , but ... as a lib to do that could make re-baking live iso's faster in docker.. 
go compiled right tends to be mounds faster. 

ability to iso dump and squashfile also nice to have.

**Comment by mholt** [comment]
Hmm, I don't think ISO/Squashfile is on my roadmap, but we could re-open this to discuss a contribution if someone was serious about implementing this functionality.
