### ISSUE TITLE
Zip output path set to non-existing directory casues failure

### ISSUE THREAD

**Issue by kevlut** [mholt/archiver#61]
This may be able to be a non-issue, but I was expecting that when I passed a directory location that did not yet exist, the directory would get created and the zip would still get output to that path.  

    err := archiver.Zip.Make(outputPath, files)

Instead, it returns an error:

> error creating [outputPath]: open [outputPath]: The system cannot find the path specified.

I created the output directory structure and the previous code worked fine.  

When zipping using a desktop application, you can provide an nonexisting output path and the directories will be created for you.  So, who should be the owner of creating the directories?

I'm on Win10 x64

**Comment by mholt** [comment]
This is implemented in #99.
