### ISSUE TITLE
Support for Multi-part Archives

### ISSUE THREAD

**Issue by davidnewhall** [mholt/archiver#68]
I'm attempting to extract rar files that are multi-part (.rar .r01 r.02 etc). Using the `unrar` tools available out there, I just pass them a single file name (the .rar file) and they extract all the subsequent archives. I'm using `archiver` as a library and calling `archiver.Rar.Open(file, path)` then receive this error: `writing file: rardecode: archive continues in next volume`

Am I missing something, or is this support missing? Thanks!

**Comment by jyggen** [comment]
Seems like support was added in #38 but later removed in #43. Basically `OpenReader` needs to be used in order to extract multi-part archives.
