### ISSUE TITLE
Proposal: regex matching and parallel Open for multiple files support

### ISSUE THREAD

**Issue by A-Hilaly** [mholt/archiver#73]
Hello !
Actually i'm became a frequent user of archiver since its totally generalist and efficient. The case of openning huge archives or several archives at once is bit painfull which leaded me to think about these improvements. 

**Regex matching:**
Archiving or reading archive files using simple regex match

```shell
archiver open -r *.zip mydestination
```

**Multiple targets** (for regex expressions and simple file names)
for files:

```shell
archiver open file1.zip file2.tar mydestination
```
for regex
```shell
archiver open -r *.zip *.tar mydestination
```

**distinct destinations**
```shell
# simple
archiver open file1.zip -d mydest1 file2.zip -d mydest2 
# regex
archiver open -r *.zip -d mydest1 *.tar -d mydest2
```

**parralel openning**
```shell
archiver --parallel --cores=2 open -r *.zip *.tar mydestination
```

All the examples above for multiple files Open situations. For making archives, it's not too usefull to add parralel support but regex matching might be interessting. 
```shell
archiver make -r myarchive.zip *.png
```

**Specifications**
Actually archiver is built on simple command line parser, implementing all this features might need to use Cobra or any other command line library. 

Would be glad to hear what do you think and help implementing these features !

**Comment by mholt** [comment]
Thanks for the feature request.

What do these commands actually _do_ though? If it's just a matter of working with multiple archive files, you can just run the command multiple times: once for each file.
