### ISSUE TITLE
Latest release version tag not updated

### ISSUE THREAD

**Issue by bojan-karlas** [mholt/archiver#88]
Go packaging tools that work with versions (e.g. dep) are picking up the release version `v2.0.0` from 2016. The latest code needs to be packaged in a release version that is above `2.0.0` so that it can work with the tools. Is this possible to do ASAP?

**Comment by johnarok** [comment]
@mholt @weingart should we cut one as 2.1.0 release? there are some PRs waiting to be merged around zip slip and symlink, thoughts?

**Comment by mholt** [comment]
Sure, that's probably a good idea. :+1:

**Comment by johnarok** [comment]
Thanks @weingart for cutting the release.. I have tagged a v2.1.0 to keep compatibility for Go Modules support
