### ISSUE TITLE
Potential Incompatibility with CodeDeploy

### ISSUE THREAD

**Issue by TarekAS** [mholt/archiver#96]
Having used this library to zip files for use in AWS CodeDeploy, I noticed a strange bug:
All .png files extracted by CodeDeploy have size 0 bytes. I suspect this is the same for all compressed formats. I am using the latest version of both tools.

I fixed it by removing all extensions from the compressedFormats map in zip.go.

There could be some sort of incompatibility between this archiver and the one used by CodeDeploy. I couldn't not investigate this any further due to lack of time, so I apologize for the brief explanation.

Hope this helps.

**Comment by mholt** [comment]
Thanks for the report. I wonder if CodeDeploy is ignoring in the file headers whether the file is actually compressed or not.
