### ISSUE TITLE
Slow extract for tar.xz

### ISSUE THREAD

**Issue by alexisoyama** [mholt/archiver#97]
https://github.com/ulikunitz/xz is very slow at extracting. 

https://github.com/xi2/xz is 10x faster for me. Consider using this for extraction. It doesn't support compression, so it won't be a full replace.

**Comment by mholt** [comment]
Will consider this when finishing #99.

**Comment by mholt** [comment]
Implemented in 0d66ce6b77f970dd4c6afe4cf2f91fda2f8ec2a6. Thanks!
